### ISSUE TITLE
A crash with https://www.oppetarkiv.se KeyError: 'programTitle'

### ISSUE THREAD

**Issue by MaistroX** [spaam/svtplay-dl#596] opened 2017-03-27 06:12 UTC
C:\svtplay-dl>svtplay-dl.exe https://www.oppetarkiv.se/video/1083362/spung-sasong-1-avsnitt-1-av-12 -o I:\svtplay-dl -S -M --remux -f --verbose
DEBUG [1490595133.0538793] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.oppetarkiv.se/video/1083362/spung-sasong-1-avsnitt-1-av-12'
DEBUG [1490595133.8819265] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1330842-001OA'
ERROR [1490595134.1209402] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.9.3
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 463, in main
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 194, in get_media
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 241, in get_one_media
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\service\oppetarkiv.py", line 40, in get
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\service\oppetarkiv.py", line 155, in outputfilename
KeyError: 'programTitle'
Failed to execute script svtplay-dl

**Comment by qnorsten** [comment] 2017-03-28 19:34
This is a duplicate of https://github.com/spaam/svtplay-dl/issues/593
A fix is beeing worked on in https://github.com/spaam/svtplay-dl/pull/591, for now it only affects the autogenerated filename and a temporary fix is to set your own output filename using -o or the --output parameter

**Comment by ijbh** [comment] 2017-03-29 19:31
I use mac and svtplay-dl with Brew. I can't download any movie from oppetarkiv.se. I get the following error message:

ERROR: svtplay-dl crashed
ERROR: Run again and add --verbose as an argument, to get more information
ERROR: If the error persists, you can report it at https://github.com/spaam/svtplay-dl/issues
ERROR: Include the URL used, the stack trace and the output of svtplay-dl --version in the issue

Is this the same problem? I guess I have to wait for an update?

**Comment by qnorsten** [comment] 2017-03-29 19:35
It is probably the same problem @ijbh but only way to be sure is if you run the same command as before but with the --verbose flag and check the error message.

**Comment by ijbh** [comment] 2017-03-30 23:06
I got the following message:

DEBUG [1490915105.47] /usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.oppetarkiv.se/video/12495414/st-barthelemy-var-sista-koloni'
DEBUG [1490915106.79] /usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://api.svt.se/videoplayer-api/video/1378326-001OA'
ERROR [1490915107.51] /usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py/get_one_media: version: 1.9.3
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 463, in main
    get_media(urls[0], options)
  File "/usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 194, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 241, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/service/oppetarkiv.py", line 40, in get
    self.options.output = self.outputfilename(data, self.options.output, ensure_unicode(self.get_urldata()))
  File "/usr/local/Cellar/svtplay-dl/1.9.3_1/libexec/lib/python2.7/site-packages/svtplay_dl/service/oppetarkiv.py", line 155, in outputfilename
    name = data["programTitle"]
KeyError: 'programTitle'

**Comment by MR-2** [comment] 2017-03-31 10:26
@ijbh snorsten have already mentioned a temorary solution for this. Name the output yourself by using either the -o or --output flag.

**Comment by ijbh** [comment] 2017-03-31 21:41
Could you please tell me exactly what I need to write in Terminal?

**Comment by iwconfig** [comment] 2017-04-01 00:00
Run `svtplay-dl` with the parameters (option flags, the ones with one or two dashes) you want but also add `-o` which is short for `--output` (same option) and the path and/or filename you want to have.

For example, add `-o "Saint Barthélemy - vår sista koloni"` to download the documentary movie to the current working directory (the directory that the terminal is working from). If you're just starting the terminal and running `svtplat-dl` straight away you probably are in your user home directory.

The user home directory default locations:
- Linux: `/home/<username>/` (most often)
- OSX: `/Users/<username>/`
- Windows: `C:\Users\<username>\` (i think)

If you type `pwd` in Linux or OSX or `cd` in Windows you get the current directory.

For instance, if you, @ijbh, want to save that documentary to a folder called _Movies_ which is located in your current working directory (e.g. /home/@ijbh/) you can prepend the path to the filename as such: `"Movies/Saint Barthélemy - vår sista koloni"`. If you want it somewhere in another (parent) folder relative to your current working directory you have to enter the full path, just as simple as a hierarchical structure can be. So if you want it in, lets say _/tmp_ (which is just a folder for temporary files by the way, so dont download to this place if you want to keep it) you have to prepend the filename with `"/tmp/Saint Barthélemy - vår sista koloni"`. Notice here the first `/`, in *NIX systems like Linux and OSX, that one is important because it tells us the _tmp_ folder is relative to the root of the file system just as `C:\` represent the root in Windows. The file _Saint Barthélemy - vår sista koloni_ is relative to root and the folder _tmp_ which is, in this instance, where it is located.

Remember to encapsulate the filename (and path) with quotes, double or single, if it contains any white space, else `svtplay-dl` think of each word as an arguments which it of course would not understand. Also, if you're wondering, you don't have to append the extension name (e.g. _.mp4_) to the filename. `svtplay-dl` takes care of that anyway and if you do when downloading using the DASH protocol it will throw an error at you. This is a known bug. Oh and by the way, it doesn't matter which order you put the options and arguments as long as the option is together with the argument, as in `--output path/to/filename`. Although the `http*://` url is treated without the details of an option flag, it can also be put in any order after _svtplay-dl_ like the options.

I'll end this conundrum (i hope not haha) with an example in full:
`svtplay-dl -M -o "/home/ijbh/Movies/Saint Barthélemy - vår sista koloni" https://www.oppetarkiv.se/video/12982980/saint-barthelemy-var-sista-koloni`

**Comment by Usudanix** [comment] 2017-04-09 07:52
It doesn't work with -o and quotes for me.
I get this:

>svtplay-dl https://www.oppetarkiv.se/video/5466460/ivar-kreuger-avsnitt-1-av-3 --subtitle --force --all-episodes --verbose

DEBUG [1491723744.810636] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.oppetarkiv.se/video/5466460/ivar-kreuger-avsnitt-1-av-3'
DEBUG [1491723745.661637] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.oppetarkiv.se/etikett/titel/Ivar_Kreuger/?sida=1&sort=tid_stigande&embed=true'
DEBUG [1491723745.821636] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.oppetarkiv.se/etikett/titel/Ivar_Kreuger/?sida=2&sort=tid_stigande&embed=true'
INFO [1491723746.0736363] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py/get_all_episodes: Episode 1 of 3

DEBUG [1491723746.0746367] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.oppetarkiv.se/video/5466460/ivar-kreuger-avsnitt-1-av-3'
DEBUG [1491723746.3796377] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1371552-001OA'
ERROR [1491723746.4396384] site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.9.3

Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 463, in main
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 192, in get_media
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 220, in get_all_episodes
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\__init__.py", line 241, in get_one_media
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\service\oppetarkiv.py", line 40, in get
  File "site-packages\svtplay_dl-1.9.3-py3.5.egg\svtplay_dl\service\oppetarkiv.py", line 155, in outputfilename
KeyError: 'programTitle'
Failed to execute script svtplay-dl

**Comment by qnorsten** [comment] 2017-04-09 07:54
@Usudanix  you are not using -o/--output and it will not work with --all-episodes as you can only specify an output directory and the filename will be auto generated.

**Comment by Usudanix** [comment] 2017-04-09 11:28
Tank you! 👍

**Comment by forthrin** [comment] 2017-04-20 10:14
Any ETA on a fix that makes "-A" work on oppetarkiv.se?

**Closed** 2017-04-21 20:01 UTC
