### ISSUE TITLE
viafree.se TypeError

### ISSUE THREAD

**Issue by krito** [spaam/svtplay-dl#647] opened 2017-06-20 08:32 UTC
Hello,
I get an error when i try to download episodes from the first season, but not the second. 
Thanks for a great tool!
```
svtplay-dl https://www.viafree.se/program/dokumentar/brottskod/sasong-1/319978 --verbose

DEBUG [1497947028.06] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.viafree.se/program/dokumentar/brottskod/sasong-1/319978'
DEBUG [1497947028.18] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://playapi.mtgx.tv/v3/videos/319978'
ERROR [1497947028.24] /usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py/get_one_media: version: 1.9.4
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 466, in main
    get_media(urls[0], options)
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 196, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 244, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/service/viaplay.py", line 126, in get
    self.options.output = self.outputfilename(dataj,vid, self.options.output)
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/service/viaplay.py", line 237, in outputfilename
    basename = self._autoname(data)
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/service/viaplay.py", line 255, in _autoname
    if len(dataj["format_position"]["episode"]) > 0:
TypeError: object of type 'NoneType' has no len()

```
```

svtplay-dl --version
1.9.4
```

**Comment by selepo** [comment] 2017-09-08 18:33
The episode stated above is no longer available.
I can't reproduce this on other episodes, do you have any other examples of urls that would produce the same error ?

**Comment by dentarg** [comment] 2017-09-23 23:41
Maybe this was fixed by https://github.com/spaam/svtplay-dl/commit/c1259f2c9a0e9f7dfd6093019fbb677641abc68e?

Another video, https://www.viafree.se/program/reality/paradise-hotel/sasong-8/866496 works for me with svtplay-dl 1.9.6.

Will close the issue, we can always re-open if it's still a problem.

**Closed by dentarg** 2017-09-23 23:41 UTC
