### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Kihltech** [spaam/svtplay-dl#1102] opened 2019-06-20 08:00 UTC
### svtplay-dl versions:
**svtplay-dl 2.1**

### Operating system and Python version:
Same error on fully updated Ubuntu Server 18.04.2 and Ubuntu Server 16.04.6
Python 2.7.15+ and 2.7.12 respectively
Python3 3.6.8 and 3.5.2 respectively

### What is the issue:
**svtplay-dl https://www.svtplay.se/video/22541074/for-nationens-basta/for-nationens-basta-sasong-1-vad-som-sker-i-skuggorna --verbose**

Output:
DEBUG [1561016683.2309265] /usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py/get_media: version: 2.1
DEBUG [1561016683.2320366] /usr/lib/python3/dist-packages/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1561016683.232093] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/22541074/for-nationens-basta/for-nationens-basta-sasong-1-vad-som-sker-i-skuggorna'
DEBUG [1561016683.234376] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se
DEBUG [1561016683.285447] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/22541074/for-nationens-basta/for-nationens-basta-sasong-1-vad-som-sker-i-skuggorna HTTP/1.1" 200 39824
DEBUG [1561016683.2974262] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1392192-001A'
DEBUG [1561016683.2985647] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): api.svt.se
DEBUG [1561016683.3121216] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://api.svt.se:80 "GET /videoplayer-api/video/1392192-001A HTTP/1.1" 200 807
DEBUG [1561016683.3140185] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/a198a7fc-4141-4958-9217-a30318e2f1a3/manifest.mpd'
DEBUG [1561016683.3151803] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): switcher.cdn.svt.se
DEBUG [1561016683.333856] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /a198a7fc-4141-4958-9217-a30318e2f1a3/manifest.mpd HTTP/1.1" 302 0
DEBUG [1561016683.335742] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): balancer.cdn.svt.se
DEBUG [1561016683.3529] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190606/a198a7fc-4141-4958-9217-a30318e2f1a3/manifest.mpd HTTP/1.1" 302 0
DEBUG [1561016683.355797] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): ed7.cdn.svt.se
DEBUG [1561016683.368237] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://ed7.cdn.svt.se:80 "GET /d0/se/20190606/a198a7fc-4141-4958-9217-a30318e2f1a3/manifest.mpd HTTP/1.1" 200 8574
DEBUG [1561016683.3689053] /usr/lib/python3/dist-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://svt-vod-3q.akamaized.net/d0/se/20190606/a198a7fc-4141-4958-9217-a30318e2f1a3/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2Fa198a7fc-4141-4958-9217-a30318e2f1a3%2Fmanifest.mpd'
DEBUG [1561016683.370413] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): svt-vod-3q.akamaized.net
DEBUG [1561016683.416137] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-3q.akamaized.net:80 "GET /d0/se/20190606/a198a7fc-4141-4958-9217-a30318e2f1a3/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2Fa198a7fc-4141-4958-9217-a30318e2f1a3%2Fmanifest.mpd HTTP/1.1" 200 1282
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3/dist-packages/svtplay_dl/__init__.py", line 64, in main
    get_media(urls[0], config, __version__)
  File "/usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py", line 58, in get_media
    get_one_media(stream)
  File "/usr/lib/python3/dist-packages/svtplay_dl/utils/getmedia.py", line 107, in get_one_media
    for i in streams:
  File "/usr/lib/python3/dist-packages/svtplay_dl/service/svtplay.py", line 86, in get
    for i in videos:
  File "/usr/lib/python3/dist-packages/svtplay_dl/service/svtplay.py", line 122, in _get_video
    streams = dashparse(self.config, self.http.request("get", i["url"]), i["url"], output=self.output)
  File "/usr/lib/python3/dist-packages/svtplay_dl/fetcher/dash.py", line 143, in dashparse
    return _dashparse(config, res.text, url, output, res.cookies)
  File "/usr/lib/python3/dist-packages/svtplay_dl/fetcher/dash.py", line 171, in _dashparse
    audiofiles = adaptionset(temp, url, baseurl, offset_sec, duration_sec)
  File "/usr/lib/python3/dist-packages/svtplay_dl/fetcher/dash.py", line 102, in adaptionset
    template = element[0].find("{urn:mpeg:dash:schema:mpd:2011}SegmentTemplate")
IndexError: list index out of range

**Comment by zidodiz** [comment] 2019-06-20 10:18
Same error for me as well on **1.9.11**:

svtplay-dl -A -S -t --verbose --remux **https://www.svt.se/barnkanalen/barnplay/sommarlov**
DEBUG [1561025773.27] /usr/lib/python2.7/site-packages/svtplay_dl/__init__.py/get_media: version: 1.9.11
DEBUG [1561025773.28] /usr/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.svt.se/barnkanalen/barnplay/sommarlov'
INFO [1561025773.88] /usr/lib/python2.7/site-packages/svtplay_dl/__init__.py/get_all_episodes: Episode 1 of 11
INFO [1561025773.88] /usr/lib/python2.7/site-packages/svtplay_dl/__init__.py/get_all_episodes: Url: http://www.svt.se/barnkanalen/barnplay/sommarlov/22564050
DEBUG [1561025773.88] /usr/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svt.se/barnkanalen/barnplay/sommarlov/22564050'
DEBUG [1561025774.65] /usr/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1391094-001W'
DEBUG [1561025774.77] /usr/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://switcher.cdn.svt.se/645480f0-3b6f-4ae1-8d98-e55c5e6de663/lowbw.mpd'
DEBUG [1561025774.97] /usr/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://switcher.cdn.svt.se/645480f0-3b6f-4ae1-8d98-e55c5e6de663/master-fmp4.m3u8'
DEBUG [1561025775.11] /usr/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://switcher.cdn.svt.se/645480f0-3b6f-4ae1-8d98-e55c5e6de663/master.m3u8'
DEBUG [1561025775.23] /usr/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svt-vod-10q.akamaized.net/d0/se/20190607/645480f0-3b6f-4ae1-8d98-e55c5e6de663/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F645480f0-3b6f-4ae1-8d98-e55c5e6de663%2Fmaster.m3u8'
DEBUG [1561025775.32] /usr/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://ed0.cdn.svt.se/d0/se/20190607/645480f0-3b6f-4ae1-8d98-e55c5e6de663/master.m3u8'
DEBUG [1561025775.37] /usr/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://switcher.cdn.svt.se/645480f0-3b6f-4ae1-8d98-e55c5e6de663/master-fmp4-lowbw.m3u8'
DEBUG [1561025775.49] /usr/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://switcher.cdn.svt.se/645480f0-3b6f-4ae1-8d98-e55c5e6de663/manifest.mpd'
DEBUG [1561025775.63] /usr/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svt-vod-10q.akamaized.net/d0/se/20190607/645480f0-3b6f-4ae1-8d98-e55c5e6de663/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F645480f0-3b6f-4ae1-8d98-e55c5e6de663%2Fmanifest.mpd'
Traceback (most recent call last):
  File "/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 511, in main
    get_media(urls[0], options)
  File "/usr/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 215, in get_media
    get_all_episodes(stream, copy.copy(options), url)
  File "/usr/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 244, in get_all_episodes
    get_one_media(substream, copy.copy(options))
  File "/usr/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 265, in get_one_media
    for i in streams:
  File "/usr/lib/python2.7/site-packages/svtplay_dl/service/barnkanalen.py", line 74, in get
    for i in videos:
  File "/usr/lib/python2.7/site-packages/svtplay_dl/service/svtplay.py", line 129, in _get_video
    streams = dashparse(self.options, self.http.request("get", i["url"]), i["url"])
  File "/usr/lib/python2.7/site-packages/svtplay_dl/fetcher/dash.py", line 166, in dashparse
    audiofiles = adaptionset(temp, url, baseurl, offset_sec, duration_sec)
  File "/usr/lib/python2.7/site-packages/svtplay_dl/fetcher/dash.py", line 102, in adaptionset
    template = element[0].find("{urn:mpeg:dash:schema:mpd:2011}SegmentTemplate")
IndexError: list index out of range

**Comment by Sopor** [comment] 2019-06-20 11:11
Dupe of #1065 #1068 #1070 #1075 #1080 #1084 #1085 #1091 #1093 #1094

Use latest [master](https://ci.appveyor.com/project/spaam/svtplay-dl/builds/23825288/artifacts) and it will work.

**Comment by zidodiz** [comment] 2019-06-20 11:18
True, master works. Thanks!

**Comment by Kihltech** [comment] 2019-06-20 12:58
Thanks Sopor, I can also confirm it works when compiling from source.

(although I had some issues compiling and created a ticket with suggestions: #1103)

**Comment by spaam** [comment] 2019-08-25 08:33
this is fixed in 2.2. thanks for the report <3

**Closed by spaam** 2019-08-25 08:33 UTC
