### ISSUE TITLE
Sista chansen - AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by MR-2** [spaam/svtplay-dl#452] opened 2016-09-15 07:05 UTC
After the latest commit i'm getting the following error message.

INFO [1473922873.48] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_all_episodes: Episode 8 of 83
DEBUG [1473922873.48] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.svtplay.se/video/2078227/anna-blomberg-show/avsnitt-1'
DEBUG [1473922873.72] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.svt.se/videoplayer-api/video/1362164-001A'
DEBUG [1473922873.88] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay3s-f.akamaihd.net/z/world/open/20151222/1362164-001A/PG-1362164-001A-ANNABLOMBERGSH-02_,988,240,348,456,636,1680,2796,.mp4.csmil/manifest.f4m'
DEBUG [1473922874.45] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay3m-f.akamaihd.net/i/world/open/20151222/1362164-001A/PG-1362164-001A-ANNABLOMBERGSH-02_,988,240,348,456,636,1680,2796,.mp4.csmil/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1362164-001A.m3u8'
DEBUG [1473922875.0] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://switcher.cdn.svt.se/1362164-001A.m3u8'
DEBUG [1473922875.12] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://svtplay3m-f.akamaihd.net/i/world/open/20151222/1362164-001A/PG-1362164-001A-ANNABLOMBERGSH-02_,988,240,348,456,636,1680,2796,.mp4.csmil/master.m3u8'
DEBUG [1473922875.15] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay3j-f.akamaihd.net/d/world/open/delivery/20151222/1362164-001A/dash-ondemand/PG-1362164-001A-ANNABLOMBERGSH-02-1a894f3d-7b76-336d-a7c5-16191e995f6f-ondemand.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1362164-001A.mpd'
DEBUG [1473922875.72] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://switcher.cdn.svt.se/1362164-001A.mpd'
DEBUG [1473922876.32] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://svtplay3k-f.akamaihd.net/d/world/open/delivery/20151222/1362164-001A/dash-live/PG-1362164-001A-ANNABLOMBERGSH-02-1a894f3d-7b76-336d-50ee-91f18b27f82e-live.mpd'
ERROR [1473922876.35] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: version: 1.4
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 444, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 176, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 204, in get_all_episodes
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 225, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 119, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/fetcher/dash.py", line 38, in dashparse
**AttributeError: 'NoneType' object has no attribute 'text'**

**Comment by spaam** [comment] 2016-09-16 13:36
this is a duplicate of #448. no need to have two open.

**Closed by spaam** 2016-09-16 13:36 UTC
