### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by forthrin** [spaam/svtplay-dl#668] opened 2017-09-05 18:52 UTC
I see there are several similar reports here reported in the recent months, but I'm getting this one now.

```
$ svtplay-dl http://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-1/episode-1
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 466, in main
    get_media(urls[0], options)
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 196, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 228, in get_one_media
    if not filename(stream):
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/output.py", line 128, in filename
    data = ensure_unicode(stream.get_urldata())
  File "/usr/local/Cellar/svtplay-dl/1.9.4/libexec/lib/python2.7/site-packages/svtplay_dl/service/__init__.py", line 31, in get_urldata
    self._urldata = self.http.request("get", self.url).text
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by dentarg** [comment] 2017-09-23 23:35
Maybe this was fixed by https://github.com/spaam/svtplay-dl/commit/c1259f2c9a0e9f7dfd6093019fbb677641abc68e?

Can't test the above video due to geo block but https://www.viafree.se/program/reality/paradise-hotel/sasong-8/866496 works for me with svtplay-dl 1.9.6.

Will close the issue, we can always re-open if it's still a problem.

**Closed by dentarg** 2017-09-23 23:35 UTC

**Comment by forthrin** [comment] 2017-09-24 11:38
@dentarg: Updated to 1.9.6, but `svtplay-dl` fails for both the Norwegian and Swedish URL:

```DEBUG [1506252976.04] /usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.viafree.se/program/reality/paradise-hotel/sasong-8/866496'
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 477, in main
    get_media(urls[0], options)
  File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 199, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 231, in get_one_media
    if not filename(stream):
  File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/output.py", line 128, in filename
    data = ensure_unicode(stream.get_urldata())
  File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/service/__init__.py", line 31, in get_urldata
    self._urldata = self.http.request("get", self.url).text
  File "/usr/local/Cellar/svtplay-dl/1.9.6/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py", line 56, in request
    res = Session.request(self, method, url, verify=self.verify, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 471, in request
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 581, in send
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 417, in send
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 355, in _make_request
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 325, in _raise_timeout
TypeError: __str__ returned non-string (type Error)
```

`youtube-dl` downloads both the Swedish and Norwegian URL, however it gives a warning for the Norwegian URL that may contribute to solving the problem?

    WARNING: [Viafree] episode-1: Failed to parse JSON Expecting ',' delimiter: line 1 column 10221 (char 10220)

**Comment by spaam** [comment] 2017-09-24 11:39
what url are you using?

**Comment by forthrin** [comment] 2017-09-24 11:57
- http://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-1/episode-1
- https://www.viafree.se/program/reality/paradise-hotel/sasong-8/866496

**Comment by spaam** [comment] 2017-09-24 12:04
i cant reproduce this error. what is the arguments do you use?  what does `locale` say?

**Comment by dentarg** [comment] 2017-09-24 16:06
Works for me too

```
$ svtplay-dl --http-header "X-FORWARDED-FOR=176.11.19.180" http://www.viafree.no/programmer/underholdning/paradise-hotel/sesong-1/episode-1
INFO: Selected to download hls, bitrate: 1794
INFO: Outfile: paradise-hotel.s01e01-866570-viafree.ts
[061/253][=================================............................................................................................................] ETA: 0:00:38^C

$ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"

$ uname -a
Darwin 5k 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

$ svtplay-dl --version
1.9.6
```

What OS do you use @forthrin and how did you install svtplay-dl?

**Comment by dentarg** [comment] 2017-09-24 16:07
@forthrin In any case, the error you wrote about today is not the same as your original post, so it would be best to open a new issue about it.

**Comment by forthrin** [comment] 2017-09-24 16:42
#689
