### ISSUE TITLE
Issue with 2.3

### ISSUE THREAD

**Issue by rockomannen** [spaam/svtplay-dl#1142] opened 2019-09-07 18:18 UTC
poweruser@hp:~$ svtplay-dl -S --verbose -o /media/plexshare/TV\ Shows/Fråga\ Lund/S4/ https://www.svtplay.se/video/23506942/fraga-lund/fraga-lund-sasong-4-avsnitt-1?start=auto
DEBUG [1567879953.9107237] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 2.3
DEBUG [1567879953.9129295] /usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1567879953.9130535] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/23506942/fraga-lund/fraga-lund-sasong-4-avsnitt-1?start=auto'
DEBUG [1567879953.9159756] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se
DEBUG [1567879954.0549414] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/23506942/fraga-lund/fraga-lund-sasong-4-avsnitt-1?start=auto HTTP/1.1" 200 28775
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 64, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 56, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 106, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 82, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 296, in extrametadata
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2019-09-03T02:00:00+02:00' does not match format '%Y-%m-%dT%H:%M:%S%z'

**Comment by Sopor** [comment] 2019-09-07 18:32
Dupe of #1137

**Comment by spaam** [comment] 2019-09-07 19:59
2.4 is be released now with the fixes.

**Closed by spaam** 2019-09-07 19:59 UTC
