### ISSUE TITLE
-A doesn't work with tabs (on SVT Play)

### ISSUE THREAD

**Issue by augustjanse** [spaam/svtplay-dl#514] opened 2016-12-21 09:42 UTC
For example, it would be nice if

`svtplay-dl -A http://www.svtplay.se/historieatarna?tab=klipp`

would download all the clips from the _Klipp_ tab of the _Historieätarna_ show. Right now it looks like it downloads all episodes (without clips) as if no query string had been given.

**Comment by spaam** [comment] 2016-12-21 09:50
good idea.  if the query string is present, download the clips. if not download all episodes.

**Comment by Sopor-** [comment] 2016-12-21 14:02
Then add support for downloading only a specifik season by adding season in the tab `http://www.svtplay.se/bron?tab=sasong2`

**Comment by spaam** [comment] 2017-02-02 15:21
#550 fixed this issue and it will be included in the next release later today.

**Closed by spaam** 2017-02-02 15:21 UTC

**Comment by Sopor-** [comment] 2017-04-12 00:48
@spaam I'm not sure where i should add this comment but -A doesn't work if i want to download only a season
```
$ svtplay-dl -S -A -P hls https://www.svtplay.se/plus?tab=sasong23
INFO: Episode 1 of 12
INFO: Outfile: plus.s22e04.20.okt.2016.21.00-56d6c16-svtplay.srt
INFO: Selected to download dash, bitrate: 3215
INFO: Outfile: plus.s22e04.20.okt.2016.21.00-56d6c16-svtplay.m4a
[127/581][========================......................................................................................] ETA: 0:00:10
```
As you can see it will find 12 episodes but season 23 only have 6 episodes and you can also see it will start with plus.s22.
If i remove -A i get this message:
`ERROR: This mode is not supported anymore. need the url with the video`
I even tried to use --include-clips but it still won't work. The only help i could find was for --include-clips so i believe it can't be any more switches i need to use than -A if i want to download a whole season?
Is it me doing something wrong or what? I'm running latest master.

**Comment by qnorsten** [comment] 2017-04-12 07:48
@Sopor that seems to be linked to https://github.com/spaam/svtplay-dl/issues/584
as my own developbranch in my own fork works fine. 
I will try to add my own fix for both this and that problem later today. So can @spaam change it/improve it later if he likes.

**Comment by qnorsten** [comment] 2017-04-12 19:25
@Sopor-  can you try with latest master and see if it fixes the issue?:) 
Commit https://github.com/spaam/svtplay-dl/commit/9fe6b951cc4a68b514d04648f4244172d9faf8d7 should fix this.

**Comment by Sopor-** [comment] 2017-04-12 21:47
@qnorsten It seems to work perfect 👍 
```
$ svtplay-dl -S -A -P hls https://www.svtplay.se/plus?tab=sasong23
INFO: Episode 1 of 6
INFO: Selected to download hls, bitrate: 2796
INFO: Outfile: plus.s23e01.tis.7.mar.20.30-4303ef8-svtplay.ts
```

**Comment by Sopor-** [comment] 2017-04-12 21:56
@qnorsten but i did run into a new issue. Swedish characters only show up as diamond and a question mark inside it :(

**Comment by Sopor-** [comment] 2017-04-12 22:18
If i use 1.9.3 it look like this
```
1
00:00:00,080 --> 00:00:05,240
Ska vi lägga ett bud? Vill du?

2
00:00:05,400 --> 00:00:08,320
-Jag kommer ju till sommaren.
-Jag vet.

3
00:00:14,000 --> 00:00:19,400
Wilma Persson drunknade inte i älven,
kropp flyttades dit efter hennes död.
```

**Comment by qnorsten** [comment] 2017-04-13 12:23
@Sopor-  which OS and what version of python are you running? As I am not able to reproduce your problem with either python2 or python3 on windows 10. 
It looks like some sort of encoding error on your part. My last commit should not affect the subtitle encoding in anyway.

**Comment by Sopor-** [comment] 2017-04-13 20:25
@qnorsten  I run it on Ubuntu with python 2.7.6 and before i pulled your commit it worked perfect.
This is last week download:
```
1
00:00:41,240 --> 00:00:45,080
Här är det! Wilma!

2
00:00:45,240 --> 00:00:48,120
Wilma, här är det. Kom.

3
00:00:49,440 --> 00:00:52,800
Kolla.

4
00:00:52,960 --> 00:00:56,000
Enligt koordinaterna
ska det vara exakt här. 
```
I also tried it on Windows and here it seems to work but i do prefer to use it on my Ubuntu. I'm not a python coder so i don't know why it is not working anymore.
I tried last week's episode  in case something has been changed on tv4 but as you can see here it is now wrong here too when running latest commit.
```
1
00:00:41,240 --> 00:00:45,080
H�r �r det! Wilma!

2
00:00:45,240 --> 00:00:48,120
Wilma, h�r �r det. Kom.

3
00:00:49,440 --> 00:00:52,800
Kolla.

4
00:00:52,960 --> 00:00:56,000
Enligt koordinaterna
ska det vara exakt h�r.
```

**Comment by Sopor-** [comment] 2017-04-13 21:25
It seems to work on Viafree
```
1
0:00:17,360 --> 0:00:21,080
Det är väldigt svårt att beskriva
hur panik känns.

2
0:00:21,160 --> 0:00:23,680
Jag vill bara gråta.

3
0:00:23,760 --> 0:00:29,520
Verkligt mod handlar om att
utsätta sig för det man fruktar mest.
```

**Comment by Sopor-** [comment] 2017-04-15 23:07
TV4 will also have it...
```
1
00:01:07,760 --> 00:01:11,280
<i>Tre och en halv vecka,</i>
<i>tv� kontinenter�</i>

2
00:01:11,360 --> 00:01:14,400
<i>�fem l�nder,</i>
<i>en � och drygt 1 400 mil.</i>
```

**Comment by qnorsten** [comment] 2017-04-17 00:53
@Sopor-  I think you are better off creating a new issue for this problem and asking @spaam  to look at it. Cause I have no idea why you are having that problem.
