### ISSUE TITLE
No subtitle on tv4play with latest master

### ISSUE THREAD

**Issue by bpmildh** [spaam/svtplay-dl#923] opened 2018-07-03 20:38 UTC
I did install from latest source to try tv4play and video worked fine but it does not find subtitles:

svtplay-dl --require-subtitle --verbose https://www.tv4play.se/program/badhotellet/3961521
version: 1.9.11

DEBUG [1530645721.2735667] /usr/local/lib/python3.5/dist-packages/svtplay_dl-1.9.11-py3.5.egg/svtplay_dl/utils/getmedia.py/get_media: version: 1.9.11
DEBUG [1530645721.275273] /usr/local/lib/python3.5/dist-packages/svtplay_dl-1.9.11-py3.5.egg/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1530645721.2753766] /usr/local/lib/python3.5/dist-packages/svtplay_dl-1.9.11-py3.5.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/program/badhotellet/3961521'
INFO [1530645721.2809675] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se
DEBUG [1530645721.6726081] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: "GET /program/badhotellet/3961521 HTTP/1.1" 200 7917
DEBUG [1530645721.682137] /usr/local/lib/python3.5/dist-packages/svtplay_dl-1.9.11-py3.5.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://playback-api.b17g.net/media/3961521?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine'
INFO [1530645721.6852002] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): playback-api.b17g.net
DEBUG [1530645722.183964] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: "GET /media/3961521?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine HTTP/1.1" 200 912
DEBUG [1530645722.1853678] /usr/local/lib/python3.5/dist-packages/svtplay_dl-1.9.11-py3.5.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://lbs-usp-hls-vod.cmore.se/vod/904a7/b1exoarglee(3961521_ISMUSP).ism/b1exoarglee(3961521_ISMUSP).m3u8'
INFO [1530645722.189291] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): lbs-usp-hls-vod.cmore.se
DEBUG [1530645722.431084] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: "GET /vod/904a7/b1exoarglee(3961521_ISMUSP).ism/b1exoarglee(3961521_ISMUSP).m3u8 HTTP/1.1" 302 0
INFO [1530645722.437667] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): cmoreseusphlsvod56.akamaized.net
DEBUG [1530645722.646631] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: "GET /vod/904a7/b1exoarglee(3961521_ISMUSP).ism/b1exoarglee(3961521_ISMUSP).m3u8 HTTP/1.1" 200 633
INFO [1530645722.6824603] /usr/local/lib/python3.5/dist-packages/svtplay_dl-1.9.11-py3.5.egg/svtplay_dl/utils/getmedia.py/get_one_media: No subtitles available

**Comment by MR-2** [comment] 2018-07-04 11:19
@bpmildh this issue is a duplicate of #909, having two issues isn't necessary.

**Closed** 2018-07-04 15:15 UTC
