### ISSUE TITLE
All Episodes flag don't work on TV4play anymore

### ISSUE THREAD

**Issue by GreveTess** [spaam/svtplay-dl#1546] opened 2023-06-27 21:34 UTC
### svtplay-dl versions:

svtplay-dl 4.24

### Operating system and Python version:

Windows 10
Python 3.8.10

### What is the issue:

Trying to download ALL episodes on TV4Play does not seem to work any more.
I have tried multiple URL's including
https://www.tv4play.se/program/9937e914fb8c1b66cac3/top-dog
https://www.tv4play.se/program/e560a10921357483f685/a-million-little-things

C:\Users\Tess>svtplay-dl -A --verbose https://www.tv4play.se/program/e560a10921357483f685/a-million-little-things
DEBUG [1687899048.3374865] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.24
DEBUG [1687899048.340479] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service_init_.py/init: service: tv4play
DEBUG [1687899048.3414788] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.tv4play.se/program/e560a10921357483f685/a-million-little-things'
DEBUG [1687899048.343478] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/new_conn: Starting new HTTPS connection (1): [www.tv4play.se:443](http://www.tv4play.se:443/)
DEBUG [1687899048.7031767] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/make_request: [https://www.tv4play.se:443](https://www.tv4play.se/) "GET /program/e560a10921357483f685/a-million-little-things HTTP/1.1" 200 None
Traceback (most recent call last):
File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts_startup.py", line 130, in run
File "C:\hostedtoolcache\windows\Python\3.8.10\x64\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
File "bin\svtplay-dl", line 7, in
File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl_init.py", line 69, in main
File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 61, in get_media
File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 79, in get_all_episodes
File "D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\tv4play.py", line 136, in find_all_episodes
KeyError: 'allSeasonLinks'

Thank you in advance, your work is appreciated.

**Comment by spaam** [comment] 2023-06-27 22:00
if they going to update this every other week i will remove this feature. i dont want to babysit this.

**Comment by Vinylwalk3r** [comment] 2023-07-09 21:00
I can confirm this issue, I got this too on both my Win11 install and a dockerized install on my server. 
And as a added bonus, there seems to be a "KeyError: "data"" for tv4play.se as well.

`Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3.11/site-packages/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/lib/python3.11/site-packages/svtplay_dl/utils/getmedia.py", line 63, in get_media
    get_one_media(stream)
  File "/usr/lib/python3.11/site-packages/svtplay_dl/utils/getmedia.py", line 112, in get_one_media
    for i in streams:
  File "/usr/lib/python3.11/site-packages/svtplay_dl/service/tv4play.py", line 63, in get
    vid = res.json()["data"]["series"]["suggestedEpisode"]["episode"]["id"]
          ~~~~~~~~~~^^^^^^^^
KeyError: 'data'`

**Comment by spaam** [comment] 2023-07-18 22:55
4.25 have a fix for this

**Closed by spaam** 2023-07-18 22:55 UTC
