### ISSUE TITLE
problem with some videoes from viafree.no published after 27.09.2016

### ISSUE THREAD

**Issue by orjano** [spaam/svtplay-dl#461] opened 2016-09-28 08:37 UTC
It is no longer possible to download files published on viafree.no on 27.09.2016 and later. Files published before this date still works. Tested with git version of svtplay-dl dated 11.9 and 27.9, both with the same error message.

Command:
 svtplay-dl 'http://www.viafree.no/programmer/mat/masterchef-norges-beste-hobbykokk/sesong-2/episode-14' --verbose

Error message:
DEBUG [1475050928.32] /usr/local/bin/svtplay-dl/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.viafree.no/programmer/mat/masterchef-norges-beste-hobbykokk/sesong-2/episode-14'
ERROR [1475050928.6] /usr/local/bin/svtplay-dl/svtplay_dl/__init__.py/get_one_media: version: 1.5-2-gfc9600b
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 444, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 178, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 225, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/viaplay.py", line 91, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/viaplay.py", line 76, in _get_video_id
ValueError: invalid literal for int() with base 10: 'sesong-2'

**Comment by MR-2** [comment] 2016-09-28 10:22
It works for me now. But i have had this issue with other urls on viafree but i think it might be an publishing issue on their behalf.

**Comment by orjano** [comment] 2016-09-28 10:34
Did some more testing on videos published today and yesterday, and the following 3 links give me error, the rest worked without a problem. So it might be a publishing issue.
These are the 3 links i had problems with:
http://www.viafree.no/programmer/mat/masterchef-norges-beste-hobbykokk/sesong-2/episode-14
http://www.viafree.no/programmer/livsstil/ekstrem-oppussing-usa/sesong-8/episode-19
http://www.viafree.no/programmer/underholdning/wingman/sesong-1/episode-4

**Comment by spaam** [comment] 2016-09-28 10:42
@orjano this is really weird. it works here too. going to try something to see if it works

**Comment by MR-2** [comment] 2016-09-28 10:44
The first and the last works fine now with svtplay-dl. However the middle one looks a bit funny in the api. Think it might be some issues with fetching the RTMP that is only available for the Ekstrem series.

**Comment by spaam** [comment] 2016-09-28 10:49
@orjano: please try master to see if it fixed the issue :)

**Comment by spaam** [comment] 2016-09-28 10:50
@MR-2  interesting

**Comment by MR-2** [comment] 2016-09-28 10:53
They have some issue with the ekstrem series because i get an error message when i try to play it thru their own website. So i think they have had some general publishing issues the last hours at least.

**Comment by orjano** [comment] 2016-09-28 10:56
The error message is gone, but i now downloads the wrong episode on the two links that were broken.

orjan@server:~/orjannet$ svtplay-dl http://www.viafree.no/programmer/mat/masterchef-norges-beste-hobbykokk/sesong-2/episode-14
INFO: Selected to download hls, bitrate: 3619
INFO: Outfile: masterchef-norges-beste-hobbykokk.s2e2-765160-tv3play.ts
[261/261][================================================================================================================================] ETA: 0:00:00
orjan@server:~/orjannet$ svtplay-dl http://www.viafree.no/programmer/underholdning/wingman/sesong-1/episode-4
INFO: Selected to download hls, bitrate: 2788
INFO: Outfile: wingman.s1e1-765107-tv3play.ts
[101/101][================================================================================================================================] ETA: 0:00:00

**Comment by spaam** [comment] 2016-09-28 10:57
haha.. fixed one issue. get some few more bugs yay :)

**Comment by spaam** [comment] 2016-09-28 11:20
@orjano i cant reproduce that error. can you show give me the info from -v ?

**Comment by orjano** [comment] 2016-09-28 11:28
The other episodes in the same series still download the correct episode, it's only the broken ones that download a completely different episode.
Here is the verbose output from the two problem videos:
https://orjan.net/masterchef-s02e14.txt
https://orjan.net/wingman-s01e04.txt

**Comment by orjano** [comment] 2016-09-28 11:32
Just some system specs:
Slackware x64 14.2
python 2.7.11
rtmpdump 2.4 (git 11.09.2016)
pycrypto 2.6.1
requests 2.11.1
ffmpeg 3.1.3

**Comment by MR-2** [comment] 2016-09-28 11:42
@orjano I can't reproduce that either. Are you sure you are using master?

**Comment by orjano** [comment] 2016-09-28 12:22
I don't know much about git, but i entered the svtplay-dl folder and run "git branch" and master was the only branch listed and was selected. I did try to download svtplay-dl for windows just to test it out, and the masterchef episode that failed on my server also failed on windows 1.5 version. 

Here is the verbose output from the windows svtplay-dl 1.5:
E:\>svtplay-dl.exe http://www.viafree.no/programmer/mat/masterchef-norges-beste-hobbykokk/sesong-2/episode-14 --verbose
DEBUG [1475065183.961594] site-packages\svtplay_dl-1.5-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.viafree.no/programmer/mat/masterchef-norges-beste-hobbykokk/sesong-2/episode-14'
ERROR [1475065184.3313048] site-packages\svtplay_dl-1.5-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.5
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "site-packages\svtplay_dl-1.5-py3.5.egg\svtplay_dl\__init__.py", line 444, in main
  File "site-packages\svtplay_dl-1.5-py3.5.egg\svtplay_dl\__init__.py", line 178, in get_media
  File "site-packages\svtplay_dl-1.5-py3.5.egg\svtplay_dl\__init__.py", line 225, in get_one_media
  File "site-packages\svtplay_dl-1.5-py3.5.egg\svtplay_dl\service\viaplay.py", line 91, in get
  File "site-packages\svtplay_dl-1.5-py3.5.egg\svtplay_dl\service\viaplay.py", line 76, in _get_video_id
ValueError: invalid literal for int() with base 10: 'sesong-2'
svtplay-dl returned -1

**Comment by spaam** [comment] 2016-09-28 12:25
anyway i will check this tonight .. need to do some work stuff first :)

**Closed** 2016-10-01 10:33 UTC
