### ISSUE TITLE
QuickTime losing a few seconds of audio a few times per minute, causing audio to drift out of sync fast

### ISSUE THREAD

**Issue by drathier** [spaam/svtplay-dl#393] opened 2016-05-16 13:46 UTC
Is this a problem with QuickTime or the output file? Same file plays without problem on vlc on same mac computer.

**Comment by spaam** [comment] 2016-05-16 13:49
from where did you download the video? :)

**Comment by drathier** [comment] 2016-05-17 10:59
http://urskola.se/Produkter/179810-Yrkesmastarna-Resan-till-VM

**Comment by spaam** [comment] 2016-06-01 21:50
i watched 6 mintues i cant see any out of sync errors. im using quicktime 10.4 (855) and ffmpeg version git-2016-05-04-e3df56f..

**Comment by dentarg** [comment] 2016-08-17 20:19
I think we should close this one, as we couldn't reproduce. If there's still a problem @drathier, we can re-open. Please provide any useful information you can think of (e.g. what QuickTime version you are using).

**Closed by dentarg** 2016-08-17 20:19 UTC

**Comment by drathier** [comment] 2016-08-18 07:21
I reverted to using vlc, which works flawlessly. If it happens again, I'll let you know with a proper bug report. Thanks for an awesome piece of software!
