### ISSUE TITLE
TV4play: No videos found. Can't find json data

### ISSUE THREAD

**Issue by mcrevo96** [spaam/svtplay-dl#1058] opened 2019-03-27 15:19 UTC
There seems to be a problem with TV4play, can't download any of the videos from there. Worked fine yesterday, but not today anymore.

I tried both URL versions, but both give the same result, for example:
https://www.tv4play.se/program/robinson/11792123
https://www.tv4play.se/program/robinson?video_id=11792123

It just gives me the error message:
No videos found. Can't find json data

The --verbose error report:

`DEBUG [1553699688.5868838] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.1`
`DEBUG [1553699688.588881] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: tv4play`
`DEBUG [1553699688.589884] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.tv4play.se/program/solsidan/3200112'`
`DEBUG [1553699688.5998871] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443`
`DEBUG [1553699689.0138762] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/solsidan/3200112 HTTP/1.1" 200 None`
`ERROR [1553699689.040883] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_one_media: No videos found. Can't find json data`

**Comment by Sopor** [comment] 2019-03-27 16:52
Yes, i can confirm this with version svtplay-dl 2.1-50-g2c3352c. I have tried older programs too but i get the same error message.

@mcrevo96 You are trying to download robinson but the error message says solsidan?

**Comment by mcrevo96** [comment] 2019-03-27 17:38
> @mcrevo96 You are trying to download robinson but the error message says solsidan?

I tried to download different series, solsidan was just the one I tried with --verbose. :)

**Comment by diskpart** [comment] 2019-03-27 19:15
Youtube-dl seems unaffected by this recent change at TV4 Play.  Just downloaded the latest episode of Sveriges mästerkock.

**Comment by Umeaboy** [comment] 2019-03-28 04:27
I see this in Linux as well and here's my output:

DEBUG [1553747227.3322568] /usr/lib/python3.5/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 2.1
DEBUG [1553747227.3371882] /usr/lib/python3.5/site-packages/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1553747227.337385] /usr/lib/python3.5/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/program/nyhetsmorgon/11976687'
DEBUG [1553747227.358998] /usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se
DEBUG [1553747228.5078802] /usr/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/nyhetsmorgon/11976687 HTTP/1.1" 200 None
ERROR [1553747228.55044] /usr/lib/python3.5/site-packages/svtplay_dl/utils/getmedia.py/get_one_media: No videos found. Can't find json data

**Comment by Sopor** [comment] 2019-03-28 10:12
> Youtube-dl seems unaffected by this recent change at TV4 Play. Just downloaded the latest episode of Sveriges mästerkock.

@diskpart yes, but youtube-dl can't download subtitles from TV4 and for some reason they won't merge  support for it from a working pull request either :(

**Comment by snix47** [comment] 2019-03-30 16:42
Same here
ERROR: No videos found. Can't find json data

**Comment by radclif** [comment] 2019-04-01 18:58
Same error here.

**Comment by mcrevo96** [comment] 2019-04-04 13:26
> Same error here. Also same error in youtube-dl for me.

youtube-dl seems to work fine for me and have been using that in the meantime.

**Comment by Umeaboy** [comment] 2019-04-08 06:34
TV4 Play gives me the same result now as well.

**Comment by spaam** [comment] 2019-04-08 21:25
this is fixed in master.  i will release 2.2 tomorrow or the day after.

**Closed** 2019-04-08 21:25 UTC

**Comment by Umeaboy** [comment] 2019-04-08 22:34
Thank you so much for that. :)

**Comment by Sopor** [comment] 2019-04-08 23:06
I have only tested a few episodes, but the subtitle sometimes seems to be out of sync. Anyone else that noticed it with this issue fixed?

**Comment by Bofinken** [comment] 2019-05-06 15:49
Provade detta på Windows och fick något fel..

.\svtplay-dl.exe -S https://www.tv4play.se/program/blue-bloods/11867002
ERROR: No videos found. Can't find json data

**Comment by Umeaboy** [comment] 2019-05-06 18:08
> Provade detta på Windows och fick något fel..
> 
> .\svtplay-dl.exe -S https://www.tv4play.se/program/blue-bloods/11867002
> ERROR: No videos found. Can't find json data

Det beror på att du måste kompilera en ny version med patchen.
Då ska det fungera.

**Comment by Sopor** [comment] 2019-05-06 19:27
@Bofinken Use latest [master ](https://ci.appveyor.com/project/spaam/svtplay-dl/builds/23825288/artifacts) and it will work.
