### ISSUE TITLE
httplib.BadStatusLine

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#181] opened 2014-11-19 13:27 UTC
I have a script that i run and yesterday when i was running it i notice that the script halted for 30 seconds and then i got this error and it continues to the next program. I can't tell you what channel it was but maybe you can find out what is wrong without that information?
```
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 5, in <module>
    pkg_resources.run_script('svtplay-dl==0.9.2014.11.16', 'svtplay-dl')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.9.2014.11.16-py2.7.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.9.2014.11.16-py2.7.egg/svtplay_dl/__init__.py", line 234, in main
    get_media(url, options)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.9.2014.11.16-py2.7.egg/svtplay_dl/__init__.py", line 95, in get_media
    get_one_media(substream, copy.copy(options))
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.9.2014.11.16-py2.7.egg/svtplay_dl/__init__.py", line 120, in get_one_media
    for i in streams:
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.9.2014.11.16-py2.7.egg/svtplay_dl/service/tv4play.py", line 86, in get
    streams = hdsparse(copy.copy(options), manifest)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.9.2014.11.16-py2.7.egg/svtplay_dl/fetcher/hds.py", line 43, in hdsparse
    data = get_http_data(manifest)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-0.9.2014.11.16-py2.7.egg/svtplay_dl/utils/__init__.py", line 67, in get_http_data
    response = opener.open(request)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine:
```

**Comment by dentarg** [comment] 2015-07-27 12:33
Maybe close this? The issue is very old and it sounds like it was the remote host that did something unexpected?

**Comment by olof** [comment] 2015-07-27 14:01
I agree , and I think it would be good to go over unactionable tickets and close them generally. Thanks @dentarg for looking into this :).

**Comment by Sopor-** [comment] 2015-07-27 16:03
Why close something that is not fixed? It shouldn't crash because something unexpected happens...

**Comment by olof** [comment] 2015-07-27 17:27
But you say you aren't willing/able to supply means for us to reproduce? That makes it hard to investigate. If you still experience this issue, I would suggest open a new ticket and include an URL for which you have had the issue. (I'm not closing though, I'll let @spaam decide :))

**Comment by dentarg** [comment] 2015-08-02 09:31
@Sopor- there has been [194 commits](https://github.com/spaam/svtplay-dl/compare/0.9.2014.11.16...master) to svtplay-dl since this issue was reported, if we don't know how to try to reproduce, it's impossible to act on it, it could be fixed for all we know

**Comment by dentarg** [comment] 2015-08-02 09:36
> It shouldn't crash because something unexpected happens

Yes, it's exactly what I think svtplay-dl should do when something unexpected happens :)

But yes, better error messages and/or retrying functionality are good ideas, but we should (if we don't already have) track those feature requests in other issues

**Comment by spaam** [comment] 2015-08-31 18:19
closing this. master should have a fix for this

**Closed by spaam** 2015-08-31 18:19 UTC
