### ISSUE TITLE
srt file won't get deleted after merge

### ISSUE THREAD

**Issue by Sopor** [spaam/svtplay-dl#1427] opened 2021-10-24 00:10 UTC
When i run svtplay-dl.exe like this it won't delete the srt file:

```
svtplay-dl.exe -S -M https://www.viafree.se/program/drama/providence/sasong-1/avsnitt-1
```

svtplay-dl 4.7-4-gb3fd51d

**Comment by iwconfig** [comment] 2021-11-24 21:32
This wasn't a bug. When I added the `-M` functionality I did this intentionally so that you could have the subtitle both merged and external if you want it that way. I don't understand why this is an issue really. Just don't use `-S` together with `-M` and maybe mention this distinction in the help screen.

**Comment by spaam** [comment] 2021-11-24 21:39
bah i guess i should just revert everything and only have the features i use. if people want other features they have to maintain it 🤔

**Comment by iwconfig** [comment] 2021-11-24 21:53
Well, I don't really care tbh. I just wanted to point this out because I don't understand why this was an issue to begin with.

**Comment by iwconfig** [comment] 2021-11-25 13:23
Alright, i just did a PR reverting this and added some clarifications, check out #1444 and share your thoughts if you have any objections.

Another thought, maybe because of situations like this one it is appropriate to introduce some code conventions like for example making sure to write comments sufficiently

**Comment by iwconfig** [comment] 2021-11-27 18:40
OK so, I wasn't sure but I had it in the back of my mind that this has been mentioned in the help screen before. I did a little digging and it turns out I was right. In 938ae7d9b9 for version 2.9 it was removed, without any indication of why this happened.

Before that commit it was

> merge subtitle with video/audio file with corresponding ISO639-3 language code. this invokes --remux automatically. **use with -S for external also.**

and now it is like the above without the last sentence **(in bold)**. Which is strange because the next commit, 0201222, made sure `-S` also is set to True when `-M` is True.

This is what I did from the beginning which I also commented about in that commit, but what the issue for that commit was I don't recall at all. However, with 4.9 I believe this is not needed (and it shouldn't be), hence I removed it in #1444.

Why this happened I have no idea. Presumably by accident. Anyway, I think it might have affected this situation where a minor issue is solved by removing something that's actually a (simple) feature and not a bug. Correct me if I'm wrong.

Maybe @spaam  can shed some light on this?

**Comment by bohelax** [comment] 2021-11-30 12:37
I am sorry I didn't post this as a new issue. Since it was still open I didn't know that it already had been implemented.

Also I didn't realize it would become a problem, since the old behavior seemed fine to me:

-S  :    downloads and keeps the subtitle file.
-S -M : downloads and keeps the subtitle file, and merges it too.
-M   :  downloads, but does *not* keep the subtitle file, and merges it too.

It really is a hazle having to copy the subtile file somewhere before it is deleted, every time.

//BoH

**Comment by iwconfig** [comment] 2021-11-30 13:54
- it's an obvious use case combining `-S` and `-M` imho,
- not particularly complicated,
- analogous with the `--force-subtitle` and `-S` combination,
- and sometimes really useful.

**Comment by Sopor** [comment] 2023-12-02 20:30
This is what i see after merging, but the srt file is not removed:

```
INFO: Merge audio, video and subtitle into chelsea.detective.s02e02.2.golden.years-490bf89-svtplay.mkv
INFO: Determining the language of the subtitle(s).
INFO: Language code: swe
INFO: Merging done, removing old files.
```

If it is merged it should also be removed.

**Comment by iwconfig** [comment] 2023-12-02 21:21
> This is what i see after merging, but the srt file is not removed:
> 
> ```
> INFO: Merge audio, video and subtitle into chelsea.detective.s02e02.2.golden.years-490bf89-svtplay.mkv
> INFO: Determining the language of the subtitle(s).
> INFO: Language code: swe
> INFO: Merging done, removing old files.
> ```
> 
> If it is merged it should also be removed.

So skip `-S`. Pretty simple. How is that problematic? You want it to say "merging done and all belonging files except _**any subtitles**_ are removed"?

But anyhow though, I'll share my honest view on this non-issue by quoting myself saying

> Well, I don't really care tbh.

Feel free to change it to your liking

**Closed as completed** 2023-12-04 14:12 UTC
