### ISSUE TITLE
svtplay-dl crashed when d/ling

### ISSUE THREAD

**Issue by JamesWilde** [spaam/svtplay-dl#1116] opened 2019-07-24 22:31 UTC
Mac-Mini:Det-sitter-i-väggarna james$ svtplay-dl --version
svtplay-dl 2.0

### Operating system and Python version:

MacOS High Sierra, 10.13.6
Mac-Mini:Det-sitter-i-väggarna james$ python --version
Python 2.7.10

### What is the issue:

Always include the URL you want to download and all switches you are using.
You should also add `--verbose` because it makes it much easier for use to find the issue :)

    Mac-Mini:Det-sitter-i-väggarna james$ svtplay-dl -S -v https://www.svtplay.se/video/4792378/det-sitter-i-vaggarna/det-sitter-i-vaggarna-sasong-1-avsnitt-2?start=auto
version: 2.0
DEBUG [1564006469.257183] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 2.0
DEBUG [1564006469.2668421] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1564006469.267639] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/4792378/det-sitter-i-vaggarna/det-sitter-i-vaggarna-sasong-1-avsnitt-2?start=auto'
DEBUG [1564006469.4755368] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1564006470.109289] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/4792378/det-sitter-i-vaggarna/det-sitter-i-vaggarna-sasong-1-avsnitt-2?start=auto HTTP/1.1" 200 35939
DEBUG [1564006470.197421] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1369862-002A'
DEBUG [1564006470.4061959] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): api.svt.se:80
DEBUG [1564006470.604665] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://api.svt.se:80 "GET /videoplayer-api/video/1369862-002A HTTP/1.1" 200 842
DEBUG [1564006470.608448] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/d36b1b6b-b241-4460-908a-5668ec1227c5/master-fmp4.m3u8'
DEBUG [1564006470.684947] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): switcher.cdn.svt.se:80
DEBUG [1564006470.7805882] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /d36b1b6b-b241-4460-908a-5668ec1227c5/master-fmp4.m3u8 HTTP/1.1" 302 0
DEBUG [1564006470.8162692] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): balancer.cdn.svt.se:80
DEBUG [1564006470.901425] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/world/20190721/d36b1b6b-b241-4460-908a-5668ec1227c5/master-fmp4.m3u8 HTTP/1.1" 302 0
DEBUG [1564006470.945589] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): ed4.cdn.svt.se:80
DEBUG [1564006471.041594] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://ed4.cdn.svt.se:80 "GET /d0/world/20190721/d36b1b6b-b241-4460-908a-5668ec1227c5/master-fmp4.m3u8 HTTP/1.1" 200 2744
DEBUG [1564006471.043249] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/d36b1b6b-b241-4460-908a-5668ec1227c5/master-fmp4-lowbw.m3u8'
DEBUG [1564006471.08917] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /d36b1b6b-b241-4460-908a-5668ec1227c5/master-fmp4-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1564006471.133885] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/world/20190721/d36b1b6b-b241-4460-908a-5668ec1227c5/master-fmp4-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1564006471.171346] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://ed4.cdn.svt.se:80 "GET /d0/world/20190721/d36b1b6b-b241-4460-908a-5668ec1227c5/master-fmp4-lowbw.m3u8 HTTP/1.1" 200 1727
DEBUG [1564006471.1733718] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/d36b1b6b-b241-4460-908a-5668ec1227c5/master.m3u8'
DEBUG [1564006471.2326558] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /d36b1b6b-b241-4460-908a-5668ec1227c5/master.m3u8 HTTP/1.1" 302 0
DEBUG [1564006471.2724428] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/world/20190721/d36b1b6b-b241-4460-908a-5668ec1227c5/master.m3u8 HTTP/1.1" 302 0
DEBUG [1564006471.362124] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://ed4.cdn.svt.se:80 "GET /d0/world/20190721/d36b1b6b-b241-4460-908a-5668ec1227c5/master.m3u8 HTTP/1.1" 200 2723
DEBUG [1564006471.365015] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://svt-vod-1r.akamaized.net/d0/world/20190721/d36b1b6b-b241-4460-908a-5668ec1227c5/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2Fd36b1b6b-b241-4460-908a-5668ec1227c5%2Fmaster.m3u8'
DEBUG [1564006471.679499] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): svt-vod-1r.akamaized.net:80
DEBUG [1564006471.766746] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-1r.akamaized.net:80 "GET /d0/world/20190721/d36b1b6b-b241-4460-908a-5668ec1227c5/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2Fd36b1b6b-b241-4460-908a-5668ec1227c5%2Fmaster.m3u8 HTTP/1.1" 200 657
DEBUG [1564006471.7769878] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://ed4.cdn.svt.se/d0/world/20190721/d36b1b6b-b241-4460-908a-5668ec1227c5/master.m3u8'
DEBUG [1564006471.819411] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://ed4.cdn.svt.se:80 "GET /d0/world/20190721/d36b1b6b-b241-4460-908a-5668ec1227c5/master.m3u8 HTTP/1.1" 200 2723
DEBUG [1564006471.829748] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/d36b1b6b-b241-4460-908a-5668ec1227c5/master-lowbw.m3u8'
DEBUG [1564006471.872213] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /d36b1b6b-b241-4460-908a-5668ec1227c5/master-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1564006471.912193] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/world/20190721/d36b1b6b-b241-4460-908a-5668ec1227c5/master-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1564006471.962189] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://ed4.cdn.svt.se:80 "GET /d0/world/20190721/d36b1b6b-b241-4460-908a-5668ec1227c5/master-lowbw.m3u8 HTTP/1.1" 200 1714
DEBUG [1564006471.964791] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/d36b1b6b-b241-4460-908a-5668ec1227c5/manifest.mpd'
DEBUG [1564006471.993058] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /d36b1b6b-b241-4460-908a-5668ec1227c5/manifest.mpd HTTP/1.1" 302 0
DEBUG [1564006472.03231] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/world/20190721/d36b1b6b-b241-4460-908a-5668ec1227c5/manifest.mpd HTTP/1.1" 302 0
DEBUG [1564006472.073772] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://ed4.cdn.svt.se:80 "GET /d0/world/20190721/d36b1b6b-b241-4460-908a-5668ec1227c5/manifest.mpd HTTP/1.1" 200 12555
DEBUG [1564006472.111028] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://svt-vod-1r.akamaized.net/d0/world/20190721/d36b1b6b-b241-4460-908a-5668ec1227c5/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2Fd36b1b6b-b241-4460-908a-5668ec1227c5%2Fmanifest.mpd'
DEBUG [1564006472.162478] /usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-1r.akamaized.net:80 "GET /d0/world/20190721/d36b1b6b-b241-4460-908a-5668ec1227c5/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2Fd36b1b6b-b241-4460-908a-5668ec1227c5%2Fmanifest.mpd HTTP/1.1" 200 1634
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/svtplay_dl/__init__.py", line 63, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 56, in get_media
    get_one_media(stream)
  File "/usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 105, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/svtplay_dl/service/svtplay.py", line 85, in get
    for i in videos:
  File "/usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/svtplay_dl/service/svtplay.py", line 121, in _get_video
    streams = dashparse(self.config, self.http.request("get", i["url"]), i["url"], output=self.output)
  File "/usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 165, in dashparse
    audiofiles = adaptionset(temp, url, baseurl, offset_sec, duration_sec)
  File "/usr/local/Cellar/svtplay-dl/2.0/libexec/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 102, in adaptionset
    template = element[0].find("{urn:mpeg:dash:schema:mpd:2011}SegmentTemplate")
IndexError: list index out of range
Mac-Mini:Det-sitter-i-väggarna james$

**Comment by Sopor** [comment] 2019-07-24 23:14
Dupe of #1065 #1068 #1070 #1075 #1080 #1084 #1085 #1091 #1093 #1094 #1095 #1102 #1107 #1109 #1112 #1113

Windows use latest [master](https://ci.appveyor.com/project/spaam/svtplay-dl/builds/23825288/artifacts) and it will work.

If you are running Linux, BSD or macOS use [this](https://svtplay-dl.se/install/source/).

macOS can try follow [this](https://github.com/spaam/svtplay-dl/issues/1070#issuecomment-488087551) guide.

**Comment by spaam** [comment] 2019-08-25 08:30
this is fixed in 2.2. thanks for the report <3

**Closed by spaam** 2019-08-25 08:30 UTC
