### ISSUE TITLE
Crash when downloading from svtplay.se

### ISSUE THREAD

**Issue by HenricE** [spaam/svtplay-dl#1112] opened 2019-07-10 13:22 UTC
### svtplay-dl versions:

svtplay-dl 2.1

### Operating system and Python version:

Linux vbox-nuc 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

Python 2.7.15+

### What is the issue:

Always include the URL you want to download and all switches you are using.
You should also add `--verbose` because it makes it much easier for use to find the issue :)

svtplay-dl --verbose https://www.svtplay.se/video/22751598/poldark/poldark-sasong-4-avsnitt-1?start=auto
DEBUG [1562764939.8727283] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 2.1
DEBUG [1562764939.8764768] /usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1562764939.8767989] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/22751598/poldark/poldark-sasong-4-avsnitt-1?start=auto'
DEBUG [1562764939.881311] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se
DEBUG [1562764940.8112626] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/22751598/poldark/poldark-sasong-4-avsnitt-1?start=auto HTTP/1.1" 200 37645
DEBUG [1562764940.8450859] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1392880-001A'
DEBUG [1562764940.8499897] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): api.svt.se
DEBUG [1562764940.9846725] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://api.svt.se:80 "GET /videoplayer-api/video/1392880-001A HTTP/1.1" 200 758
DEBUG [1562764940.9876523] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/4073a925-bf25-40da-ac35-589111ffb9ac/master-fmp4-lowbw.m3u8'
DEBUG [1562764940.9910896] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): switcher.cdn.svt.se
DEBUG [1562764941.0159962] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /4073a925-bf25-40da-ac35-589111ffb9ac/master-fmp4-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1562764941.020795] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): balancer.cdn.svt.se
DEBUG [1562764941.0525503] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190703/4073a925-bf25-40da-ac35-589111ffb9ac/master-fmp4-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1562764941.066941] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): ed7.cdn.svt.se
DEBUG [1562764941.1095629] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://ed7.cdn.svt.se:80 "GET /d0/se/20190703/4073a925-bf25-40da-ac35-589111ffb9ac/master-fmp4-lowbw.m3u8 HTTP/1.1" 200 1425
DEBUG [1562764941.111466] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/4073a925-bf25-40da-ac35-589111ffb9ac/manifest.mpd'
DEBUG [1562764941.124823] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /4073a925-bf25-40da-ac35-589111ffb9ac/manifest.mpd HTTP/1.1" 302 0
DEBUG [1562764941.1437545] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190703/4073a925-bf25-40da-ac35-589111ffb9ac/manifest.mpd HTTP/1.1" 302 0
DEBUG [1562764941.167537] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://ed7.cdn.svt.se:80 "GET /d0/se/20190703/4073a925-bf25-40da-ac35-589111ffb9ac/manifest.mpd HTTP/1.1" 200 12345
DEBUG [1562764941.1687942] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://svt-vod-7i.akamaized.net/d0/se/20190703/4073a925-bf25-40da-ac35-589111ffb9ac/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F4073a925-bf25-40da-ac35-589111ffb9ac%2Fmanifest.mpd'
DEBUG [1562764941.1726358] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): svt-vod-7i.akamaized.net
DEBUG [1562764941.238981] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-7i.akamaized.net:80 "GET /d0/se/20190703/4073a925-bf25-40da-ac35-589111ffb9ac/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F4073a925-bf25-40da-ac35-589111ffb9ac%2Fmanifest.mpd HTTP/1.1" 200 1597
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 64, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 58, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 107, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 86, in get
  File "/usr/local/bin/svtplay-dl/svtplay_dl/service/svtplay.py", line 122, in _get_video
  File "/usr/local/bin/svtplay-dl/svtplay_dl/fetcher/dash.py", line 143, in dashparse
  File "/usr/local/bin/svtplay-dl/svtplay_dl/fetcher/dash.py", line 171, in _dashparse
  File "/usr/local/bin/svtplay-dl/svtplay_dl/fetcher/dash.py", line 102, in adaptionset
IndexError: list index out of range

**Comment by Sopor** [comment] 2019-07-10 14:17
Dupe of #1065 #1068 #1070 #1075 #1080 #1084 #1085 #1091 #1093 #1094 #1095 #1102 #1107 #1109

Windows use latest [master](https://ci.appveyor.com/project/spaam/svtplay-dl/builds/23825288/artifacts) and it will work.

If you are running Linux, BSD or macOS use [this](https://svtplay-dl.se/install/source/).

macOS can try follow [this](https://github.com/spaam/svtplay-dl/issues/1070#issuecomment-488087551) guide.

**Comment by max204** [comment] 2019-07-21 10:12
I've got svtplay-dl 2.1-53-gd33186e on Mac and it doesn't seem to work fully when you include subtitles. Without subtitles, it works.

This is the error I get when running this command:
svtplay-dl -A -M --verbose https://www.svtplay.se/blue-planet-ii

[299/299][===================================================================================================================================================================] ETA: 0:00:00DEBUG [1563703203.2861052] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'http://svt-vod-2g.akamaized.net/d0/world/20190718/910a1b8c-ef4c-44e0-9886-d8776b0f7115/hls-video6/hls-video6-299.ts'
DEBUG [1563703203.373655] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-2g.akamaized.net:80 "GET /d0/world/20190718/910a1b8c-ef4c-44e0-9886-d8776b0f7115/hls-video6/hls-video6-299.ts HTTP/1.1" 200 3381932

INFO [1563703203.853528] /usr/local/bin/svtplay-dl/svtplay_dl/postprocess/__init__.py/merge: Merge audio, video and subtitle into blue.planet.ii.s02e01.ett.enda.hav-992d761-svtplay.ts
INFO [1563703203.853703] /usr/local/bin/svtplay-dl/svtplay_dl/postprocess/__init__.py/sublanguage: Determining the language of the subtitle.
DEBUG [1563703203.875655] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): whatlanguage.herokuapp.com:443
DEBUG [1563703204.237414] /usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://whatlanguage.herokuapp.com:443 "POST / HTTP/1.1" 200 26
INFO [1563703204.239656] /usr/local/bin/svtplay-dl/svtplay_dl/postprocess/__init__.py/sublanguage: Language code: swe
INFO [1563703210.9600608] /usr/local/bin/svtplay-dl/svtplay_dl/postprocess/__init__.py/merge: Merging done, removing old files.
INFO [1563703211.192223] /usr/local/bin/svtplay-dl/svtplay_dl/postprocess/__init__.py/remux: Muxing blue.planet.ii.s02e01.ett.enda.hav-992d761-svtplay.ts and merging its subtitle into blue.planet.ii.s02e01.ett.enda.hav-992d761-svtplay.mp4
INFO [1563703211.192468] /usr/local/bin/svtplay-dl/svtplay_dl/postprocess/__init__.py/sublanguage: Determining the language of the subtitle.
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/svtplay-dl/__main__.py", line 13, in <module>
  File "/usr/local/bin/svtplay-dl/svtplay_dl/__init__.py", line 64, in main
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 54, in get_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 85, in get_all_episodes
  File "/usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py", line 223, in get_one_media
  File "/usr/local/bin/svtplay-dl/svtplay_dl/postprocess/__init__.py", line 125, in remux
  File "/usr/local/bin/svtplay-dl/svtplay_dl/postprocess/__init__.py", line 91, in sublanguage
  File "/usr/local/bin/svtplay-dl/svtplay_dl/postprocess/__init__.py", line 43, in query
  File "/usr/local/bin/svtplay-dl/svtplay_dl/postprocess/__init__.py", line 38, in parse
FileNotFoundError: [Errno 2] No such file or directory: 'blue.planet.ii.s02e01.ett.enda.hav-992d761-svtplay.srt'

**Comment by spaam** [comment] 2019-08-25 08:31
this is fixed in 2.2. thanks for the report <3

**Closed by spaam** 2019-08-25 08:31 UTC
