### ISSUE TITLE
Unicode comparison error when downloading Hem till Gården

### ISSUE THREAD

**Issue by ullgren** [spaam/svtplay-dl#300] opened 2015-11-04 08:15 UTC
Version: Latest master from github

```
$ svtplay-dl -A -S  http://www.tv4play.se/program/hem-till-g%C3%A5rden
INFO: Episode 1 of 10
/usr/lib/python2.7/urllib.py:1288: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return ''.join(map(quoter, s))
Script crashed. please run the script again and add --verbose as an argument
Make an issue with the url you used and include the stacktrace. please include the version of the script
```

**Comment by ullgren** [comment] 2015-11-04 10:23
Seems to work now after installing some additional pips and python libraries. See #298

**Comment by olof** [comment] 2015-11-04 10:39
hum, was this really related to ssl issues?

**Comment by ullgren** [comment] 2015-11-04 17:33
No you are correct the issue is still there in the latest version from the master branch. I was testing different tags and versions must have had an older checked out when it was working.

So the unicode error is there in "0.20.2015.10.25-10-g4093102".
However moving back to "0.20.2015.09.13" then the unicode error is not present.

Running Ubuntu 14.04

**Comment by spaam** [comment] 2015-11-04 17:35
the commit 917f276e4189146 broke it. line 126 is the issue

**Comment by spaam** [comment] 2015-11-18 17:17
i can't reproduce the issue right now. closing this

**Closed by spaam** 2015-11-18 17:17 UTC
