### ISSUE TITLE
Support for Svt: barnkanalen

### ISSUE THREAD

**Issue by gr3p** [spaam/svtplay-dl#1323] opened 2021-02-16 07:42 UTC
### ISSUE:
ERROR: No videos found. Can't find video info.

**Comment by pythonuser3856** [comment] 2021-02-17 06:17
Same result when I try.

**svtplay-dl version:**
svtplay-dl snap-shot 20210216 225742 (python code)

**Operating system and Python version:**
python 3.7.4
windows 8.1 64-bit

**The error trace that I get:**
DEBUG [1613541998.7442403] e:\svtplaydll\svtplay-dl_sshot_20210216_225742py\svtplay_dl\utils\getmedia.py/get_media: version: 3.0-1-g0bcf162
DEBUG [1613541998.7442403] e:\svtplaydll\svtplay-dl_sshot_20210216_225742py\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1613541998.7442403] e:\svtplaydll\svtplay-dl_sshot_20210216_225742py\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.svtplay.se/kanaler/svtbarn'
DEBUG [1613541998.7442403] C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1613541998.822385] C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /kanaler/svtbarn HTTP/1.1" 200 56646
DEBUG [1613541998.8379982] e:\svtplaydll\svtplay-dl_sshot_20210216_225742py\svtplay_dl\utils\http.py/request: HTTP getting 'https://api.svt.se/video/ch-svtbarn'

DEBUG [1613541998.8379982] C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): api.svt.se:443
DEBUG [1613541998.9630234] C:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py/_make_request: https://api.svt.se:443 "GET /video/ch-svtbarn HTTP/1.1" 404 38
ERROR [1613541998.9630234] e:\svtplaydll\svtplay-dl_sshot_20210216_225742py\svtplay_dl\utils\getmedia.py/get_one_media: No videos found.

**Comment by spaam** [comment] 2021-02-17 18:11
@gr3p what url are you using? if you want it fixed. i need to know the url and what version you are using.

@pythonuser3856 your issue is not the same as @gr3p

**Comment by gr3p** [comment] 2021-02-17 20:29
@spaam Hello, example url: https://www.svt.se/barnkanalen/barnplay/bolibompafamiljen/8LdL6rr/
Versions tested: 2.4-2 and 3.0.

**Comment by SweDennis** [comment] 2021-02-19 18:51
Confirmed on:

```
dennis@Lenovo:~$ svtplay-dl --version
svtplay-dl 3.0+1.g0bcf162
dennis@Lenovo:~$ 

dennis@Lenovo:~$ python --version
Python 3.8.5
dennis@Lenovo:~$ 

dennis@Lenovo:~$ svtplay-dl https://www.svt.se/barnkanalen/barnplay/bolibompafamiljen/8LdL6rr/ --verbose
DEBUG [1613760678.5098455] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.0+1.g0bcf162-py3.8.egg/svtplay_dl/utils/getmedia.py/get_media: version: 3.0+1.g0bcf162
DEBUG [1613760678.5101702] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.0+1.g0bcf162-py3.8.egg/svtplay_dl/service/__init__.py/__init__: service: barnkanalen
DEBUG [1613760678.5102305] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.0+1.g0bcf162-py3.8.egg/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svt.se/barnkanalen/barnplay/bolibompafamiljen/8LdL6rr/'
DEBUG [1613760678.5116887] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svt.se:443
DEBUG [1613760679.16708] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.svt.se:443 "GET /barnkanalen/barnplay/bolibompafamiljen/8LdL6rr/ HTTP/1.1" 200 None
ERROR [1613760679.28412] /usr/local/lib/python3.8/dist-packages/svtplay_dl-3.0+1.g0bcf162-py3.8.egg/svtplay_dl/utils/getmedia.py/get_one_media: No videos found. Can't find video info.
dennis@Lenovo:~$ 

```

**Comment by pythonuser3856** [comment] 2021-02-21 09:25
If you're eager to get access you could try out the snapshot version 20210220_151316 until you get an official reply. That version of svtplay-dl allows at least me to access the link in the example above:

py e:\svtplaydll\svtplay-dl_sshot_20210220_151316py\__main__.py https://www.svt.
se/barnkanalen/barnplay/bolibompafamiljen/8LdL6rr/
-
INFO: Selected to download dash, bitrate: 5269 format: h264
INFO: Outfile: bolibompafamiljen.s03e02.kalas-8ldl6rr-barnkanalen.m4a
[91/91][========================================] ETA: 0:00:00
INFO: Outfile: bolibompafamiljen.s03e02.kalas-8ldl6rr-barnkanalen.mp4
[91/91][========================================] ETA: 0:00:00
INFO: Merge audio and video into bolibompafamiljen.s03e02.kalas-8ldl6rr-barnkanalen.mp4
INFO: Merging done, removing old files.

**Comment by SweDennis** [comment] 2021-02-21 09:42
Works for me too since yesterday

```
dennis@Lenovo:~$ svtplay-dl --version
svtplay-dl 3.0+5.g8cd5793
dennis@Lenovo:~$ python --version
Python 3.8.5
dennis@Lenovo:~$ 

```

**Comment by gr3p** [comment] 2021-02-21 13:15
@pythonuser3856 Nice, it works like a charm!

**Comment by pythonuser3856** [comment] 2021-02-21 22:12
gr3p: I'm just a user of this application but noticed that a fix was at hand.
Note that you who put this issue-report is free to close it...

**Closed** 2021-02-22 10:53 UTC
