### ISSUE TITLE
svt-dl crashes when downloading the first part of a series of two

### ISSUE THREAD

**Issue by WeatherOrNothing** [spaam/svtplay-dl#1113] opened 2019-07-11 20:39 UTC
### What is the issue:
I'm trying 
svtplay-dl.exe  http://www.svtplay.se/video/20957624/vetenskapens-varld/vetenskapens-varld-varlden-i-vaxthuset-del-1
but svtplay-dl crashes.

When I download part 2
svtplay-dl.exe  http://www.svtplay.se/video/20957624/vetenskapens-varld/vetenskapens-varld-varlden-i-vaxthuset-del-2
everything is ok.

>svtplay-dl.exe --verbose http://www.svtplay.se/video/20957624/vetenskapens-varld/vetenskapens-varld-varlden-i-vaxthuset-del-1
DEBUG [1562874493.6627352] c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 2.1
DEBUG [1562874493.6627352] c:\projects\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: svtplay
DEBUG [1562874493.6627352] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://www.svtplay.se/video/20957624/vetenskapens-varld/vetenskapens-varld-varlden-i-vaxthuset-del-1'
DEBUG [1562874493.6627352] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): www.svtplay.se:80
DEBUG [1562874493.7721107] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://www.svtplay.se:80 "GET /video/20957624/vetenskapens-varld/vetenskapens-varld-varlden-i-vaxthuset-del-1 HTTP/1.1" 307 0
DEBUG [1562874493.787738] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1562874494.6158605] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/20957624/vetenskapens-varld/vetenskapens-varld-varlden-i-vaxthuset-del-1 HTTP/1.1" 200 None
DEBUG [1562874494.662737] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1391963-005A'
DEBUG [1562874494.662737] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): api.svt.se:80
DEBUG [1562874494.7877362] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://api.svt.se:80 "GET /videoplayer-api/video/1391963-005A HTTP/1.1" 200 809
DEBUG [1562874494.8033621] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/dee9cb80-c0e7-403f-a540-382856fadcdd/master-lowbw.m3u8'
DEBUG [1562874494.8033621] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): switcher.cdn.svt.se:80
DEBUG [1562874494.834613] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /dee9cb80-c0e7-403f-a540-382856fadcdd/master-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1562874494.8502407] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): svt-vod-5.secure.footprint.net:80
DEBUG [1562874494.881488] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://svt-vod-5.secure.footprint.net:80 "GET /d0/se/20190627/dee9cb80-c0e7-403f-a540-382856fadcdd/master-lowbw.m3u8 HTTP/1.1" 200 1713
DEBUG [1562874494.881488] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://switcher.cdn.svt.se/dee9cb80-c0e7-403f-a540-382856fadcdd/manifest.mpd'
DEBUG [1562874494.9127378] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /dee9cb80-c0e7-403f-a540-382856fadcdd/manifest.mpd HTTP/1.1" 302 0
DEBUG [1562874494.9127378] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTP connection (1): svt-vod-5i.akamaized.net:80
DEBUG [1562874494.9596114] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://svt-vod-5i.akamaized.net:80 "GET /d0/se/20190627/dee9cb80-c0e7-403f-a540-382856fadcdd/manifest.mpd HTTP/1.1" 200 1639
DEBUG [1562874494.975238] c:\projects\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'http://svt-vod-5i.akamaized.net/d0/se/20190627/dee9cb80-c0e7-403f-a540-382856fadcdd/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2Fdee9cb80-c0e7-403f-a540-382856fadcdd%2Fmanifest.mpd'
DEBUG [1562874494.990863] C:\Python35\lib\site-packages\urllib3\connectionpool.py/_make_request: http://svt-vod-5i.akamaized.net:80 "GET /d0/se/20190627/dee9cb80-c0e7-403f-a540-382856fadcdd/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2Fdee9cb80-c0e7-403f-a540-382856fadcdd%2Fmanifest.mpd HTTP/1.1" 200 1639
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Python35\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "bin/svtplay-dl", line 7, in <module>
  File "c:\projects\svtplay-dl\lib\svtplay_dl\__init__.py", line 64, in main
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 58, in get_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\utils\getmedia.py", line 107, in get_one_media
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 86, in get
  File "c:\projects\svtplay-dl\lib\svtplay_dl\service\svtplay.py", line 122, in _get_video
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 143, in dashparse
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 171, in _dashparse
  File "c:\projects\svtplay-dl\lib\svtplay_dl\fetcher\dash.py", line 102, in adaptionset
IndexError: list index out of range

**Comment by Sopor** [comment] 2019-07-11 20:57
Dupe of #1065 #1068 #1070 #1075 #1080 #1084 #1085 #1091 #1093 #1094 #1095 #1102 #1107 #1109 #1112

Windows use latest [master](https://ci.appveyor.com/project/spaam/svtplay-dl/builds/23825288/artifacts) and it will work.

If you are running Linux, BSD or macOS use [this](https://svtplay-dl.se/install/source/).

macOS can try follow [this](https://github.com/spaam/svtplay-dl/issues/1070#issuecomment-488087551) guide.

**Comment by spaam** [comment] 2019-08-25 08:31
this is fixed in 2.2. thanks for the report <3

**Closed by spaam** 2019-08-25 08:31 UTC
