### ISSUE TITLE
Download from twitch is broken

### ISSUE THREAD

**Issue by suom1** [spaam/svtplay-dl#790] opened 2018-02-08 12:08 UTC
Running on Ubuntu artful. 

`DEBUG [1518091568.95] /usr/lib/python2.7/dist-packages/svtplay_dl/__init__.py/get_media: version: 1.9.7
DEBUG [1518091568.96] /usr/lib/python2.7/dist-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://www.twitch.tv/videos/XXXXXXXXXX'
DEBUG [1518091569.01] /usr/lib/python2.7/dist-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'https://api.twitch.tv//api/channels/videos/access_token'
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/__init__.py", line 497, in main
    get_media(urls[0], options)
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/__init__.py", line 209, in get_media
    get_one_media(stream, copy.copy(options))
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/__init__.py", line 257, in get_one_media
    for i in streams:
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/service/twitch.py", line 68, in get
    for i in data:
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/service/twitch.py", line 152, in _get_channel
    hls_url = self._get_hls_url(channel)
  File "/usr/lib/python2.7/dist-packages/svtplay_dl/service/twitch.py", line 139, in _get_hls_url
    query = "token={0}&sig={1}&allow_source=true&allow_spectre=true".format(quote_plus(access['token']), access['sig'])
KeyError: 'token'
`

**Comment by MikeLund** [comment] 2018-02-13 10:19
Duplicate of https://github.com/spaam/svtplay-dl/issues/560

**Closed** 2018-02-13 11:52 UTC
