### ISSUE TITLE
Crash with -S on tv3play, missing subtitle?

### ISSUE THREAD

**Issue by magic75** [spaam/svtplay-dl#396] opened 2016-05-20 20:41 UTC
./svtplay-dl -S http://www.tv3play.se/program/the-blacklist/733238?autostart=true
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./svtplay-dl/__main__.py", line 13, in <module>
  File "./svtplay-dl/svtplay_dl/__init__.py", line 402, in main
  File "./svtplay-dl/svtplay_dl/__init__.py", line 165, in get_media
  File "./svtplay-dl/svtplay_dl/__init__.py", line 245, in get_one_media
  File "./svtplay-dl/svtplay_dl/subtitle/__init__.py", line 31, in download
  File "./svtplay-dl/svtplay_dl/subtitle/__init__.py", line 107, in sami
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 901, column 102

---
Without -S it downloads fine. I guess the subtitle is missing.

**Comment by magic75** [comment] 2016-05-26 21:26
I checked by playing the video directly on tv3play, and then the subtitle shows. So it is actually NOT missing, but svtplay-dl fails to download it.

**Comment by spaam** [comment] 2016-06-01 20:44
the issue is that the parser is crashing beacuse they have "&" in the subtitle.  the master have a fix for this and will be in a relase tomorrow

**Closed by spaam** 2016-06-01 20:44 UTC
