### ISSUE TITLE
KeyError 'default' when downloading from urplay.se

### ISSUE THREAD

**Issue by Puffin05** [spaam/svtplay-dl#1382] opened 2021-05-12 15:45 UTC
### svtplay-dl versions:

3.7

### Operating system and Python version:

MacOS Sierra 10.12.6, Python 3.7.3

### What is the issue:

Cannot download from urplay.se, returns KeyError. Same error occurs with all shows I have tried.

```
svtplay-dl https://urplay.se/program/162208-mansklighetens-sista-dagar-maskinerna-tar-over --verbose
DEBUG [1620833733.126763] /usr/local/Cellar/svtplay-dl/3.7/libexec/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 3.7
DEBUG [1620833733.128096] /usr/local/Cellar/svtplay-dl/3.7/libexec/lib/python3.9/site-packages/svtplay_dl/service/__init__.py/__init__: service: urplay
DEBUG [1620833733.1281579] /usr/local/Cellar/svtplay-dl/3.7/libexec/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://urplay.se/program/162208-mansklighetens-sista-dagar-maskinerna-tar-over'
DEBUG [1620833733.154846] /usr/local/Cellar/svtplay-dl/3.7/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): urplay.se:443
DEBUG [1620833733.410007] /usr/local/Cellar/svtplay-dl/3.7/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://urplay.se:443 "GET /program/162208-mansklighetens-sista-dagar-maskinerna-tar-over HTTP/1.1" 200 49802
DEBUG [1620833733.459095] /usr/local/Cellar/svtplay-dl/3.7/libexec/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://streaming-loadbalancer.ur.se/loadbalancer.json'
DEBUG [1620833733.479397] /usr/local/Cellar/svtplay-dl/3.7/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): streaming-loadbalancer.ur.se:443
DEBUG [1620833733.570417] /usr/local/Cellar/svtplay-dl/3.7/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://streaming-loadbalancer.ur.se:443 "GET /loadbalancer.json HTTP/1.1" 200 None
DEBUG [1620833733.572743] /usr/local/Cellar/svtplay-dl/3.7/libexec/lib/python3.9/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://streaming10.ur.se/urplay/_definst_/mp4:162000-162999/162208-26.mp4/playlist.m3u8'
DEBUG [1620833733.587744] /usr/local/Cellar/svtplay-dl/3.7/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): streaming10.ur.se:443
DEBUG [1620833733.668548] /usr/local/Cellar/svtplay-dl/3.7/libexec/lib/python3.9/site-packages/urllib3/connectionpool.py/_make_request: https://streaming10.ur.se:443 "GET /urplay/_definst_/mp4:162000-162999/162208-26.mp4/playlist.m3u8 HTTP/1.1" 200 None
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/3.7/libexec/lib/python3.9/site-packages/svtplay_dl/__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/Cellar/svtplay-dl/3.7/libexec/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py", line 61, in get_media
    get_one_media(stream)
  File "/usr/local/Cellar/svtplay-dl/3.7/libexec/lib/python3.9/site-packages/svtplay_dl/utils/getmedia.py", line 111, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/3.7/libexec/lib/python3.9/site-packages/svtplay_dl/service/urplay.py", line 52, in get
    if not (self.config.get("get_all_subtitles")) and (stream["default"]):
KeyError: 'default'
```

**Comment by pythonuser3856** [comment] 2021-05-12 16:27
I can download by using a later snapshot version 20210510_221658.

**Example download**
py c:\svtplaydll\svtplay-dl_sshot_20210510_221658py\__main__.py --subtitle --exclude "syntolkat,teckentolkat,teckensprakstolkat" https://urplay.se/program/215693-ensamma-tillsammans
-
-------------------
2021-05-12 18:21:04
-------------------
INFO: Outfile: ensamma.tillsammans.s01-215693-urplay.srt
INFO: Outfile: ensamma.tillsammans.s01-215693-urplay.ts
INFO: Selected to download hls, bitrate: 3182 format: h264
[462/462][========================================] ETA: 0:00:00
INFO: Muxing ensamma.tillsammans.s01-215693-urplay.ts into ensamma.tillsammans.s01-215693-urplay.mp4
INFO: Muxing done, removing the old file.

**Comment by Puffin05** [comment] 2021-05-12 17:31
Tried that, now some shows work, but the original one I tried with still gives the same error
https://urplay.se/program/162208-mansklighetens-sista-dagar-maskinerna-tar-over

**Comment by Puffin05** [comment] 2021-05-12 17:37
It works when downloading single shows, like this one that @pythonuser3856 tried with: 
https://urplay.se/program/215693-ensamma-tillsammans
However, it does not work with shows that have multiple episodes, like this one: 
https://urplay.se/program/162208-mansklighetens-sista-dagar-maskinerna-tar-over

**Comment by pythonuser3856** [comment] 2021-05-12 18:07
Confirmed.
Multiple downloads (using the switch "--all-episodes") does not work with URplay.se
**Example**
py c:\svtplaydll\svtplay-dl_**sshot_20210510_221658**py\__main__.py **--all-episodes** --subtitle https://urplay.se/program/162200-mansklighetens-sista-dagar-kollapsande-stjarnor
2021-05-12 19:59:14

**ERROR: Can't find json info**

I was using the python code variant of snapshot 20210510_221658
running on Windows 8.1 and python 3.8.10

**Comment by pythonuser3856** [comment] 2021-05-12 18:41
I thought so to and removed the switch "--subtitle"
Then I got was I think is the same result:

py c:\svtplaydll\svtplay-dl_sshot_**20210510_221658**py\__main__.py **--verbose** https://urplay.se/program/162200-mansklighetens-sista-dagar-kollapsande-stjarnor
DEBUG [1620844623.264796] c:\svtplaydll\svtplay-dl_sshot_20210510_221658py\svtplay_dl\utils\getmedia.py/get_media: version: 3.7-12-ga5e4166
DEBUG [1620844623.266798] c:\svtplaydll\svtplay-dl_sshot_20210510_221658py\svtplay_dl\service\__init__.py/__init__: service: urplay
DEBUG [1620844623.266798] c:\svtplaydll\svtplay-dl_sshot_20210510_221658py\svtplay_dl\utils\http.py/request: HTTP getting 'https://urplay.se/program/162200-mansklighetens-sista-dagar-kollapsande-stjarnor'
DEBUG [1620844623.2698007] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): urplay.se:443
DEBUG [1620844623.4860077] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://urplay.se:443 "GET/program/162200-mansklighetens-sista-dagar-kollapsande-stjarnor HTTP/1.1" 200 50590
DEBUG [1620844623.5340552] c:\svtplaydll\svtplay-dl_sshot_20210510_221658py\svtplay_dl\utils\http.py/request: HTTP getting 'https://streaming-loadbalancer.ur.se/loadbalancer.json'
DEBUG [1620844623.537059] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): streaming-loadbalancer.ur.se:443
DEBUG [1620844623.6281447] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://streaming-loadbalancer.ur.se:443 "GET /loadbalancer.json HTTP/1.1" 200 None
DEBUG [1620844623.6311479] c:\svtplaydll\svtplay-dl_sshot_20210510_221658py\svtplay_dl\utils\http.py/request: HTTP getting 'https://streaming10.ur.se/urplay/_definst_/mp4:162000-162999/162200-26.mp4/playlist.m3u8'
DEBUG [1620844623.6331496] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): streaming10.ur.se:443
DEBUG [1620844623.8163254] C:\Users\User name\AppData\Roaming\Python\Python38\site-packages\urllib3\connectionpool.py/_make_request: https://streaming10.ur.se:4
43 "GET /urplay/_definst_/mp4:162000-162999/162200-26.mp4/playlist.m3u8 HTTP/1.1" 200 None
Traceback (most recent call last):
  File "c:\svtplaydll\svtplay-dl_sshot_20210510_221658py\__main__.py", line 15,in <module>
    svtplay_dl.main()
  File "c:\svtplaydll\svtplay-dl_sshot_20210510_221658py\svtplay_dl\__init__.py", line 69, in main
    get_media(urls[0], config, __version__)
  File "c:\svtplaydll\svtplay-dl_sshot_20210510_221658py\svtplay_dl\utils\getmedia.py", line 62, in get_media
    get_one_media(stream)
  File "c:\svtplaydll\svtplay-dl_sshot_20210510_221658py\svtplay_dl\utils\getmedia.py", line 112, in get_one_media
    for i in streams:
  File "c:\svtplaydll\svtplay-dl_sshot_20210510_221658py\svtplay_dl\service\urplay.py", line 52, in get
    if not (self.config.get("get_all_subtitles")) and (stream["default"]):
KeyError: 'default'

**Comment by pythonuser3856** [comment] 2021-05-12 18:48
Probably since there is material at URplay which is related to learning foreign languages;
an example:
https://urplay.se/serie/200319-habla-ya

**Comment by spaam** [comment] 2021-05-12 18:50
hmm i guess i can choose swedish by default and if they want other stuff, they need to use the argumet for all subs to get that.

**Comment by pythonuser3856** [comment] 2021-05-12 18:55
I had a quick glance at some language episodes and found subtitles in swedish only,
whatever that is worth

**Comment by spaam** [comment] 2021-05-12 19:01
i committed a fix for the subtitle crash :)

**Closed** 2021-05-12 19:00 UTC

**Comment by pythonuser3856** [comment] 2021-05-12 19:38
The weblink example
https://urplay.se/program/162208-mansklighetens-sista-dagar-maskinerna-tar-over
is probably not that representative.

Download of single episodes of the example weblink works fine with the change to svtplay-dl.
But it also reveals that there is only one stream available and the resolution is 640x360. Production year is said to be 2011.
Not really up to standards by URplay for this example material.
_Perhaps the chosen weblink-example refers to old foreign material which URplay is unable to put in par with contemporary material; hence the deviating encoding ?_

**What should be noted is that other series at URplay can be downloaded individually per episode without the fix.**
The fix applied to svtplay-dl **is not needed** to retrieve https://urplay.se/program/218241-fraktfartyg-i-arktis-i-isbrytarens-spar ,production year 2020.

**However**
I always get a failure attempting to download all episodes using the switch "--all-episodes"**
There should be a ticket to address that a use of switch "--all-episodes" does not work with URplay.se
_Personally I've ignored that flaw in svtplay-dl since I'm fine with downloading one epsisode at a time._
