### ISSUE TITLE
[tv4play] 503 (Service Unavailable)

### ISSUE THREAD

**Issue by akvadrat** [spaam/svtplay-dl#1509] opened 2022-11-14 23:47 UTC
### svtplay-dl versions:

svtplay-dl --version
svtplay-dl 4.14

### Operating system and Python version:
Debian 11

python3 --version
Python 3.9.2

### What is the issue:

svtplay-dl  --verbose  https://www.tv4play.se/program/robinson/robinson-gr%C3%A4nslandet-del-6-s%C3%A4song-11/13779229
DEBUG [1668469285.0166209] /usr/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 4.14
DEBUG [1668469285.0193405] /usr/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1668469285.019494] /usr/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/program/robinson/robinson-gr%C3%A4nslandet-del-6-s%C3%A4song-11/13779229'
DEBUG [1668469285.0224533] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1668469285.4266102] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/robinson/robinson-gr%C3%A4nslandet-del-6-s%C3%A4song-11/13779229 HTTP/1.1" 200 None
DEBUG [1668469285.4331744] /usr/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://playback-api.b17g.net/media/13779229?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome'
DEBUG [1668469285.4356496] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): playback-api.b17g.net:443
**DEBUG [1668469285.6396675] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://playback-api.b17g.net:443 "GET /media/13779229?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine&browser=GoogleChrome HTTP/1.1" 503 506**
ERROR [1668469285.6406868] /usr/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_one_media: No videos found. Can't play this because the video is geoblocked or not available.

Could be due to that you need to log in to tv4play now?

**Comment by spaam** [comment] 2022-11-15 00:01
They changed the url where the video info is. Its fixed in master. There is a snapshot with the fix.  But i will release a new version tomorrow 😊

**Comment by Sopor** [comment] 2022-11-15 01:01
It seems to work now 👍

**Comment by akvadrat** [comment] 2022-11-15 06:38
Yes, tested the snapshot and it works fine. Will test the release when it is available. Thank you very much!

**Comment by JohnnyJorgensen** [comment] 2022-11-19 13:23
@spaam - Don't mean to rush you, just curious: When will the updated version be released?

**Comment by Sopor** [comment] 2022-11-19 19:47
@JohnnyJorgensen Use the latest [snapshot](https://svtplay-dl.se/download/snapshots/) if you can't wait ...

**Comment by truemrwalker** [comment] 2022-11-20 14:39
I tried to use the snapshot, but it failed too. 
I use VPN from Japan, and accessing TV4 directly does not work since you get blocked if you use VPN, but using svtplay-dl have always worked, until now... 
Just recently successfully downloaded and watched the first 4 episodes of Expedition season 2, but since episode 5 it has changed and you get the following message in the console "ERROR: No videos found. Can't play this because the video is geoblocked or not available." .. also with the latest snapshot (and the VPN set to Sweden)

**Comment by Sopor** [comment] 2022-11-20 23:57
TV4Play do required login to download videos, but not all videos require login. Maybe that is the reason you get errors?

It seems that you can download older videos, so maybe you need to enter login credentials for svtplay-dl, but I leave that part to @spaam 😊

**Comment by spaam** [comment] 2022-11-21 00:25
what are these videos that need login to download? provide a link to it if you want it to be fixed. i dont want to check 1000000 videos just to find it. i have better things to do :) 

@truemrwalker , without providing any data like the url and output from the program with the argument  `-v / --verbose`  when you trying to download the video you having issues with, i will do my best trying to find the issue while looking into a crystal ball. 🤔 interesting data that im finding 🤔.  the crystal ball telling me the reason(s) could be 1) they blocked your VPN endpoint in the last couple of days  2) something broke with your the vpn? 3) you are using an old version of the script 4) bad url?  5) its an real issue?  6) tacos with banana 🍌 is a good thing? 🤔 . as you can see there is a bunch of different variables here.  anyway without the output and url , i cant do anything.  like telling you what the issue is , fixing the program or write a better error message when that thing happen :)

Why no release in the last week?  i just wanted to do something else after my day job in the evening.  like watching some great tv shows like `star wars: andor` :) hopefully in the next day or so we can release it :)

**Comment by spaam** [comment] 2022-11-21 22:49
comrade @Sopor , i dont see any video on that page. its just a page that describe the movie / tvshow.  if you click on `titta nu` you get the correct link and it works  :) 
```
➜  lib git:(master) ✗ python3 -m svtplay_dl https://www.tv4play.se/program/a-winter-getaway/avsnitt/13771352
INFO: Outfile: a-winter-getaway.a.winter.getaway-13771352-tv4play.ts
INFO: Selected to download hls, bitrate: 2273 format: h264
[0046/1253][=====...................................................................................................................................................] ETA: 0:00:20^C
```
If you want to download that movie / tvshow on that URL you need to use -A
```
➜  lib git:(master) ✗ python3 -m svtplay_dl -A https://www.tv4play.se/program/a-winter-getaway
INFO: Episode 1 of 1
INFO: Url: https://www.tv4play.se/program/a-winter-getaway/13771352
INFO: Outfile: a-winter-getaway.a.winter.getaway-13771352-tv4play.ts
INFO: Selected to download hls, bitrate: 2273 format: h264
[0026/1253][===.....................................................................................................................................................] ETA: 0:00:19^C
```

**Comment by Sopor** [comment] 2022-11-22 15:17
@spaam I used the wrong URL, my bad 😢

Strange that `svtplay-dl` works without login/password, when `Retrospect` needs it.

**Comment by truemrwalker** [comment] 2022-11-26 15:27
I use NORDVPN with Swedish server (from Japan) and the latest version of svtplay-dl 4.15, and though I previously had no problem downloading from TV4, now, since their changes, I get geo-blocked all the time.

### svtplay-dl versions:
svtplay-dl 4.15

### Operating system:
Windows 11, 
version: 21H2

### What is the issue:
D:\Programs\Download Streams (svtplay-dl)>svtplay-dl --verbose https://www.tv4play.se/program/expeditionen/del-5-säsong-2/13758296
DEBUG [1669475556.7658076] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.15
DEBUG [1669475556.766828] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: tv4play
DEBUG [1669475556.766828] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://www.tv4play.se/program/expeditionen/del-5-säsong-2/13758296'
DEBUG [1669475556.768414] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1669475557.7110946] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /program/expeditionen/del-5-s%C3%A4song-2/13758296 HTTP/1.1" 200 None
DEBUG [1669475558.0487335] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://playback2.a2d.tv/play/13758296?service=tv4&device=browser&browser=GoogleChrome&protocol=hls%2Cdash&drm=widevine&capabilities=live-drm-adstitch-2%2Cexpired_assets'
DEBUG [1669475558.0497518] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): playback2.a2d.tv:443
DEBUG [1669475559.428072] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://playback2.a2d.tv:443 "GET /play/13758296?service=tv4&device=browser&browser=GoogleChrome&protocol=hls%2Cdash&drm=widevine&capabilities=live-drm-adstitch-2%2Cexpired_assets HTTP/1.1" 403 116
ERROR [1669475559.4285748] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_one_media: No videos found. Can't play this because the video is geoblocked or not available.

Can it be helped somehow?

**Comment by akvadrat** [comment] 2022-11-26 16:30
I tested the one above and it works fine from a swedish IP.

I guess you thought of selecting a Swedish NordVPN server to exit from ? Maybe tv4 has blacklisted known VPN servers?

**Comment by truemrwalker** [comment] 2022-11-27 02:10
> I tested the one above and it works fine from a swedish IP.
> 
> ~I guess~ you thought of selecting a Swedish NordVPN server to exit from ~?~, so maybe tv4 has blacklisted known VPN servers?

I tried 7-8 different ones, where it used to be maximum 3... so I assumed it was something more damning... but perhaps I was just very unlucky... or you were very lucky...
I will try again and see..

**Comment by R3C01L-SWE** [comment] 2022-11-27 18:49
> > I tested the one above and it works fine from a swedish IP.
> > ~I guess~ you thought of selecting a Swedish NordVPN server to exit from ~?~, so maybe tv4 has blacklisted known VPN servers?
> 
> I tried 7-8 different ones, where it used to be maximum 3... so I assumed it was something more damning... but perhaps I was just very unlucky... or you were very lucky... I will try again and see..

VPN problem. I tried with servers from 4 different providers in Sweden and they are all blocked. 

Connected to a private server over VPN and it instantly worked for the whole season of that.

**Comment by spaam** [comment] 2022-12-01 06:45
yeah. i fixed the issue to download the files without vpn.  fixing it with vpn is not really with svtplay-dl.

**Closed by spaam** 2022-12-01 06:45 UTC
