### ISSUE TITLE
SVTPlay - crashed after a few skipped episodes running -A

### ISSUE THREAD

**Issue by Sopor-** [spaam/svtplay-dl#476] opened 2016-10-16 21:04 UTC
I got this crash after running:
$ svtplay-dl -A -S http://www.svtplay.se/genikampen
but all episides except one was downloaded but i can't use `--all-last=2` anymore because it will try to download thhe two first episodes instead of the two last episodes.

```
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 5, in <module>
    pkg_resources.run_script('svtplay-dl==1.5', u'svtplay-dl')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.5-py2.7.egg/EGG-INFO/scripts/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/__init__.py", line 444, in main
    get_media(url, options)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/__init__.py", line 176, in get_media
    get_all_episodes(stream, options, url)
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/__init__.py", line 204, in get_all_episodes
    get_one_media(substream, copy.copy(options))
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/__init__.py", line 225, in get_one_media
    for i in streams:
  File "/usr/local/lib/python2.7/dist-packages/svtplay_dl-1.5-py2.7.egg/svtplay_dl/service/svtplay.py", line 47, in get
    data = data.json()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 741, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 488, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 389, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by spaam** [comment] 2016-10-16 21:12
this is a duplicate of #475. will release a new version tomorrow.

**Closed by spaam** 2016-10-16 21:12 UTC

**Comment by Sopor-** [comment] 2016-10-16 21:50
Sorry, i didn't try the new master before reporting ...

**Comment by Sopor-** [comment] 2016-10-16 21:57
Now it seems to work :)
