### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by samkdt** [spaam/svtplay-dl#1109] opened 2019-07-06 10:32 UTC
### svtplay-dl versions:

svtplay-dl 2.1

### Operating system and Python version:

Linux

Python 3.7.3

### What is the issue:

    svtplay-dl --verbose https://www.svtplay.se/video/6972877/froken-april

DEBUG [1562409036.619181] /usr/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 2.1
DEBUG [1562409036.620297] /usr/lib/python3.7/site-packages/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1562409036.6203551] /usr/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/6972877/froken-april'
DEBUG [1562409036.6216826] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1562409036.8602352] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/6972877/froken-april HTTP/1.1" 200 36801
DEBUG [1562409036.942774] /usr/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1115194-001A'
DEBUG [1562409036.9463398] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): api.svt.se:80
DEBUG [1562409037.0247126] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://api.svt.se:80 "GET /videoplayer-api/video/1115194-001A HTTP/1.1" 200 755
DEBUG [1562409037.02822] /usr/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/8113eb2c-2466-4a79-b2a1-eeb6e49247bc/master.m3u8'
DEBUG [1562409037.03185] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): switcher.cdn.svt.se:80
DEBUG [1562409037.17253] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /8113eb2c-2466-4a79-b2a1-eeb6e49247bc/master.m3u8 HTTP/1.1" 302 0
DEBUG [1562409037.1763406] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): balancer.cdn.svt.se:80
DEBUG [1562409037.2645707] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190624/8113eb2c-2466-4a79-b2a1-eeb6e49247bc/master.m3u8 HTTP/1.1" 302 0
DEBUG [1562409037.269901] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): ed2.cdn.svt.se:80
DEBUG [1562409037.3448837] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://ed2.cdn.svt.se:80 "GET /d0/se/20190624/8113eb2c-2466-4a79-b2a1-eeb6e49247bc/master.m3u8 HTTP/1.1" 200 2548
DEBUG [1562409037.3460345] /usr/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://svt-vod-4l.akamaized.net/d0/se/20190624/8113eb2c-2466-4a79-b2a1-eeb6e49247bc/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F8113eb2c-2466-4a79-b2a1-eeb6e49247bc%2Fmaster.m3u8'
DEBUG [1562409037.3501174] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): svt-vod-4l.akamaized.net:80
DEBUG [1562409037.4448614] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-4l.akamaized.net:80 "GET /d0/se/20190624/8113eb2c-2466-4a79-b2a1-eeb6e49247bc/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F8113eb2c-2466-4a79-b2a1-eeb6e49247bc%2Fmaster.m3u8 HTTP/1.1" 200 611
DEBUG [1562409037.4534593] /usr/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://ed2.cdn.svt.se/d0/se/20190624/8113eb2c-2466-4a79-b2a1-eeb6e49247bc/master.m3u8'
DEBUG [1562409037.4928546] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://ed2.cdn.svt.se:80 "GET /d0/se/20190624/8113eb2c-2466-4a79-b2a1-eeb6e49247bc/master.m3u8 HTTP/1.1" 200 2548
DEBUG [1562409037.5014315] /usr/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/8113eb2c-2466-4a79-b2a1-eeb6e49247bc/master-fmp4-lowbw.m3u8'
DEBUG [1562409037.5364733] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /8113eb2c-2466-4a79-b2a1-eeb6e49247bc/master-fmp4-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1562409037.5765333] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190624/8113eb2c-2466-4a79-b2a1-eeb6e49247bc/master-fmp4-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1562409037.6168957] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://ed2.cdn.svt.se:80 "GET /d0/se/20190624/8113eb2c-2466-4a79-b2a1-eeb6e49247bc/master-fmp4-lowbw.m3u8 HTTP/1.1" 200 1727
DEBUG [1562409037.6182415] /usr/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/8113eb2c-2466-4a79-b2a1-eeb6e49247bc/manifest.mpd'
DEBUG [1562409037.6525278] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /8113eb2c-2466-4a79-b2a1-eeb6e49247bc/manifest.mpd HTTP/1.1" 302 0
DEBUG [1562409037.6926987] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://balancer.cdn.svt.se:80 "GET /d0/se/20190624/8113eb2c-2466-4a79-b2a1-eeb6e49247bc/manifest.mpd HTTP/1.1" 302 0
DEBUG [1562409037.7331736] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://ed2.cdn.svt.se:80 "GET /d0/se/20190624/8113eb2c-2466-4a79-b2a1-eeb6e49247bc/manifest.mpd HTTP/1.1" 200 17400
DEBUG [1562409037.7428918] /usr/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://svt-vod-4l.akamaized.net/d0/se/20190624/8113eb2c-2466-4a79-b2a1-eeb6e49247bc/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F8113eb2c-2466-4a79-b2a1-eeb6e49247bc%2Fmanifest.mpd'
DEBUG [1562409037.7850797] /usr/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-4l.akamaized.net:80 "GET /d0/se/20190624/8113eb2c-2466-4a79-b2a1-eeb6e49247bc/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F8113eb2c-2466-4a79-b2a1-eeb6e49247bc%2Fmanifest.mpd HTTP/1.1" 200 2070
Traceback (most recent call last):
  File "/usr/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/lib/python3.7/site-packages/svtplay_dl/__init__.py", line 64, in main
    get_media(urls[0], config, __version__)
  File "/usr/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 58, in get_media
    get_one_media(stream)
  File "/usr/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 107, in get_one_media
    for i in streams:
  File "/usr/lib/python3.7/site-packages/svtplay_dl/service/svtplay.py", line 86, in get
    for i in videos:
  File "/usr/lib/python3.7/site-packages/svtplay_dl/service/svtplay.py", line 122, in _get_video
    streams = dashparse(self.config, self.http.request("get", i["url"]), i["url"], output=self.output)
  File "/usr/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 143, in dashparse
    return _dashparse(config, res.text, url, output, res.cookies)
  File "/usr/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 171, in _dashparse
    audiofiles = adaptionset(temp, url, baseurl, offset_sec, duration_sec)
  File "/usr/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 102, in adaptionset
    template = element[0].find("{urn:mpeg:dash:schema:mpd:2011}SegmentTemplate")
IndexError: list index out of range

**Comment by Sopor** [comment] 2019-07-07 11:15
Yes you have and the problem is that you haven't search for `list index out of range`

Dupe of #1065 #1068 #1070 #1075 #1080 #1084 #1085 #1091 #1093 #1094 #1095 #1102

Windows use latest [master](https://ci.appveyor.com/project/spaam/svtplay-dl/builds/23825288/artifacts) and it will work.

If you are running Linux, BSD or macOS use [this](https://svtplay-dl.se/install/source/).

macOS can try follow [this](https://github.com/spaam/svtplay-dl/issues/1070#issuecomment-488087551) guide.

**Comment by spaam** [comment] 2019-08-25 08:32
this is fixed in 2.2. thanks for the report <3

**Closed by spaam** 2019-08-25 08:32 UTC
