### ISSUE TITLE
Issue downloading (audio-only) from urplay.se 

### ISSUE THREAD

**Issue by andersqvist** [spaam/svtplay-dl#1480] opened 2022-06-09 12:00 UTC
### svtplay-dl versions:
svtplay-dl 4.13-1-g487c7fe

### Operating system and Python version:

Windows 10, 21H2, Python 3.10.5

### What is the issue:

Hi,

As far as I can read in the documentation, urplay.se is supported, but I have run into a problem. If i'm trying to use svtplay-dl on a URL where there is no video-file, it gives an error  (ERROR: No videos found.)

From the Options page, I found     --only-audio    which I tried, but same result. 

Do I need to change something (add extra options etc.) or are audio-only URL's just not available?

https://urplay.se/program/225641-hjarta-och-hjarna-i-foten

Cheers!
/Anders.

Always include the URL you want to download and all switches you are using.
You should also add `--verbose` because it makes it much easier for use to find the issue :)

.\svtplay-dl.exe --verbose  https://urplay.se/program/225641-hjarta-och-hjarna-i-foten
DEBUG [1654775505.1096122] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_media: version: 4.13-1-g487c7fe
DEBUG [1654775505.1106124] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\service\__init__.py/__init__: service: urplay
DEBUG [1654775505.1106124] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://urplay.se/program/225641-hjarta-och-hjarna-i-foten'
DEBUG [1654775505.1126137] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): urplay.se:443
DEBUG [1654775505.2806406] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://urplay.se:443 "GET /program/225641-hjarta-och-hjarna-i-foten HTTP/1.1" 200 52405
DEBUG [1654775505.3306298] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\http.py/request: HTTP getting 'https://streaming-loadbalancer.ur.se/loadbalancer.json'
DEBUG [1654775505.332042] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_new_conn: Starting new HTTPS connection (1): streaming-loadbalancer.ur.se:443
DEBUG [1654775505.5171638] C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\urllib3\connectionpool.py/_make_request: https://streaming-loadbalancer.ur.se:443 "GET /loadbalancer.json HTTP/1.1" 200 None
ERROR [1654775505.5211987] D:\a\svtplay-dl\svtplay-dl\lib\svtplay_dl\utils\getmedia.py/get_one_media: No videos found.

**Comment by spaam** [comment] 2022-06-09 12:07
this is a valid bug. many other sites like svtplay.se have the audio and video in separate files. the issue is that i forgot about these type of streams when audio and video is in the same file. urplay.se have that type of files. i have some idea how to do it, it should be easy to fix  🤔

**Comment by spaam** [comment] 2022-06-09 20:13
this is fixed in master. it will be in the next version :)

**Closed by spaam** 2022-06-09 20:13 UTC
