### ISSUE TITLE
svtplay-dl breaks on parameters in url in svtplay.se

### ISSUE THREAD

**Issue by bpmildh** [spaam/svtplay-dl#1367] opened 2021-04-21 20:34 UTC
svtplay-dl breaks on parameters in url in svtplay.se, as ...?info=visa or ...?id=xyz

This is a new behavior, I'm not sure if it's svtplay-dl och svtplay.se that have changed, but it breaks my automator/applescript setup. 

Example urls
https://www.svtplay.se/video/30570534/snoanglar/snoanglar-sasong-1-avsnitt-2?info=visa
https://www.svtplay.se/video/30680418/snoanglar/snoanglar-sasong-1-avsnitt-3?id=8ZmqrVY

svtplay-dl replies
no matches found: https://www.svtplay.se/video/30570534/snoanglar/snoanglar-sasong-1-avsnitt-2?info=visa
no matches found: https://www.svtplay.se/video/30680418/snoanglar/snoanglar-sasong-1-avsnitt-3?id=8ZmqrVY

You get those parameters in the url when you click on an episode in a series page, first example "Mer om programmet" and second example "Avsnitt..." or episode thumbnail.

The simple solution is of course to delete the parameters and the question mark manually in terminal as these parameters don't really mean anything to svtplay-dl, but it would be better if they where ignored.

svtplay-dl 3.6 (Homebrew)
MacOS 11.2.3

**Comment by spaam** [comment] 2021-04-21 20:44
cant reproduce this. it works great

```
xprmnt svtplay-dl-dev/lib ‹bb9c419*› » python3 -m svtplay_dl https://www.svtplay.se/video/30570534/snoanglar/snoanglar-sasong-1-avsnitt-2\?info\=visa
INFO: Selected to download dash, bitrate: 5789 format: h264-51
INFO: Outfile: snoanglar.s01e02.avsnitt.2-3ee86a6-svtplay.m4a
[009/864][=................................................................................................................................................................] ETA: 0:00:58^C
xprmnt svtplay-dl-dev/lib ‹bb9c419*› » python3 -m svtplay_dl https://www.svtplay.se/video/30680418/snoanglar/snoanglar-sasong-1-avsnitt-3\?id\=8ZmqrVY                                             130 ↵
INFO: Selected to download dash, bitrate: 5761 format: h264-51
INFO: Outfile: snoanglar.s01e03.avsnitt.3-dbd7210-svtplay.m4a
[009/910][=................................................................................................................................................................] ETA: 0:00:54^C
xprmnt svtplay-dl-dev/lib ‹bb9c419*› » git describe
3.6
xprmnt svtplay-dl-dev/lib ‹bb9c419*› »
```

**Comment by spaam** [comment] 2021-04-21 20:49
removing the [query string](https://en.wikipedia.org/wiki/Query_string), it will brake other stuff that people use with the `-A` argument to only like download a specific reason.

**Comment by R3C01L-SWE** [comment] 2021-04-21 20:56
Not sure if this is a ZSH thing but I can confirm it.

But also that the solution for some reason seems to be to add " " around the link. See below for result on my end...

```
greyfox@MBP ~ % svtplay-dl https://www.svtplay.se/video/30570534/snoanglar/snoanglar-sasong-1-avsnitt-2?info=visa
zsh: no matches found: https://www.svtplay.se/video/30570534/snoanglar/snoanglar-sasong-1-avsnitt-2?info=visa
greyfox@MBP ~ % svtplay-dl https://www.svtplay.se/video/30680418/snoanglar/snoanglar-sasong-1-avsnitt-3?id=8ZmqrVY 
zsh: no matches found: https://www.svtplay.se/video/30680418/snoanglar/snoanglar-sasong-1-avsnitt-3?id=8ZmqrVY
greyfox@MBP ~ % svtplay-dl "https://www.svtplay.se/video/30680418/snoanglar/snoanglar-sasong-1-avsnitt-3?id=8ZmqrVY"
INFO: Episode 1 of 10
INFO: Url: http://www.svtplay.se/video/30570370/snoanglar/snoanglar-sasong-1-avsnitt-1
```

**Comment by bpmildh** [comment] 2021-04-22 04:57
ZSH is a propably the source of my problem, I switched terminal from Bash recently.  Citation marks is maybe a possible solution for me, I have to rewrite my script or switch back to Bash. 

I also notice that in Spaams test the question mark and equals sign are escaped with backslash, adding those manually in my terminal also make it works.

**Comment by bpmildh** [comment] 2021-04-22 17:59
My stuff works again after adding citation marks to the script. I can't tell if zsh or svtplay-dl handles things wrong, but this can be closed as resolved for my part.

A conclusion is that if the url have parameters, and you use zsh, the parameters either have to be removed, escape the special characters or put the whole url in citation.

;-)

**Comment by spaam** [comment] 2021-04-22 18:11
great. its a user issue , closing this :)

**Closed by spaam** 2021-04-22 18:11 UTC
