### ISSUE TITLE
local variable 'total' referenced before assignment

### ISSUE THREAD

**Issue by Usudanix** [spaam/svtplay-dl#518] opened 2017-01-04 20:38 UTC
Get the error:
"local variable 'total' referenced before assignment"

When running this:
svtplay-dl http://www.svtplay.se/dinosaurietaget --subtitle --all-episodes --stream-priority=dash --force --exclude=s01e01,s01e02,s01e03,s01e04,s01e05,s01e06,s01e07,s01e08,s01e09,s01e10,s01e11,s01e12,s01e13,s01e14,s01e15,s01e16,s01e17,s01e18,s01e19,s01e26,s01e27,s01e28,s01e29,s01e30,s01e31,s01e32,s01e33,s01e34,s01e36,s02e01,s02e02,s02e03,s02e04,s02e05,s02e45,s02e49,s02e50,s02e51

Output::
DEBUG [1483561726.455533] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.svtplay.se/dinosaurietaget'
INFO [1483561726.583536] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_all_episodes: Episode 1 of 33
DEBUG [1483561726.5840318] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.svtplay.se/video/112407/dinosaurietaget'
ERROR [1483561726.7010336] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_one_media: Excluding video
INFO [1483561726.7030334] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_all_episodes: Episode 2 of 33
DEBUG [1483561726.7040348] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.svtplay.se/video/112884/dinosaurietaget'
ERROR [1483561726.818032] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_one_media: Excluding video
INFO [1483561726.8195326] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_all_episodes: Episode 3 of 33
DEBUG [1483561726.8210323] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.svtplay.se/video/116417/dinosaurietaget'
ERROR [1483561726.9385335] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_one_media: Excluding video
INFO [1483561726.940033] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_all_episodes: Episode 4 of 33
DEBUG [1483561726.9415336] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.svtplay.se/video/1498353/dinosaurietaget'
ERROR [1483561727.0690334] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_one_media: Excluding video
INFO [1483561727.0710363] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_all_episodes: Episode 5 of 33
DEBUG [1483561727.0720325] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.svtplay.se/video/1501342/dinosaurietaget'
ERROR [1483561727.2395332] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_one_media: Excluding video
INFO [1483561727.2410407] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_all_episodes: Episode 6 of 33
DEBUG [1483561727.2420356] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.svtplay.se/video/40795/dinosaurietaget'
ERROR [1483561727.3575325] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_one_media: Excluding video
INFO [1483561727.3595333] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_all_episodes: Episode 7 of 33
DEBUG [1483561727.3600357] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.svtplay.se/video/40879/dinosaurietaget'
ERROR [1483561727.472533] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_one_media: Excluding video
INFO [1483561727.4745371] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_all_episodes: Episode 8 of 33
DEBUG [1483561727.4755318] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.svtplay.se/video/46808/dinosaurietaget'
ERROR [1483561727.6420362] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_one_media: Excluding video
INFO [1483561727.6440358] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_all_episodes: Episode 9 of 33
DEBUG [1483561727.6445374] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.svtplay.se/video/47971/dinosaurietaget'
ERROR [1483561727.773034] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_one_media: Excluding video
INFO [1483561727.7745357] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_all_episodes: Episode 10 of 33
DEBUG [1483561727.775536] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.svtplay.se/video/50997/dinosaurietaget'
ERROR [1483561727.8960316] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_one_media: Excluding video
INFO [1483561727.8980336] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_all_episodes: Episode 11 of 33
DEBUG [1483561727.8990338] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.svtplay.se/video/51943/dinosaurietaget'
ERROR [1483561728.019533] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_one_media: Excluding video
INFO [1483561728.021034] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_all_episodes: Episode 12 of 33
DEBUG [1483561728.0225334] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.svtplay.se/video/52005/dinosaurietaget'
DEBUG [1483561728.1415367] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://svtplay1e-f.akamaihd.net/i/se/open/20161220/1132934-035A/PG-1132934-035A-DINOSAURTRAIN-01_,988,240,348,456,636,1680,2796,.mp4.csmil/master.m3u8?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1132934-035A.m3u8&cc1=name%3DSvenska%7Edefault%3Dyes%7Eforced%3Dno%7Euri%3Dhttp%3A%2F%2Fmedia.svt.se%2Fdownload%2Fmcc%2Ftest%2Fcore-prd%2FSUB-1132934-035A-DINOSAURIETAGET%2Findex.m3u8%7Elang%3Dsv'
DEBUG [1483561728.2925324] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://switcher.cdn.svt.se/1132934-035A.m3u8'
DEBUG [1483561728.3960333] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://svtplay1e-f.akamaihd.net/i/se/open/20161220/1132934-035A/PG-1132934-035A-DINOSAURTRAIN-01_,988,240,348,456,636,1680,2796,.mp4.csmil/master.m3u8'
DEBUG [1483561728.4395342] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://svtplay1k-f.akamaihd.net/d/se/open/delivery/20161220/1132934-035A/dash-live/PG-1132934-035A-DINOSAURTRAIN-01-16fc641c-f64e-4ef7-950b-1726e9411ffe-1a894f3d-be21-336d-0da0-df7509eb63e9-live.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1132934-035A.mpd'
ERROR [1483561728.5120327] site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.8
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py", line 444, in main
  File "site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py", line 176, in get_media
  File "site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py", line 204, in get_all_episodes
  File "site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\__init__.py", line 225, in get_one_media
  File "site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\service\svtplay.py", line 89, in get
  File "site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\fetcher\dash.py", line 61, in dashparse
  File "site-packages\svtplay_dl-1.8-py3.5.egg\svtplay_dl\fetcher\dash.py", line 109, in parsesegments
UnboundLocalError: local variable 'total' referenced before assignment
svtplay-dl returned -1

**Comment by selepo** [comment] 2017-09-09 08:00
@Usudanix : I can't reproduce the error with the latest version (master). Do you still have this issue, or should the issue be closed ?

**Comment by Usudanix** [comment] 2017-12-04 21:14
@selepo : Please close it. The problem is gone in the latest update. Many thanks for your great effort!

**Comment by Sopor-** [comment] 2017-12-04 21:38
@Usudanix You can close it by yourself :)

**Closed** 2018-02-13 21:25 UTC
