### ISSUE TITLE
Error when trying to download from svtplay.se

### ISSUE THREAD

**Issue by Zcalman** [spaam/svtplay-dl#532] opened 2017-01-26 18:17 UTC
This error happend to me when i tried to download from svtplay on Windows 10.
First i run the old version (1.8) with same error, found the new version on homepage and replaced the old one but still same error.

Debug:
C:\svtplay-dl>svtplay-dl.exe --verbose http://www.svtplay.se/video/11794422/al-pitcher-fy-fan-sverige/al-pitcher-fy-fan-sverige-avsnitt-1?start=auto
DEBUG [1485454600.859203] site-packages\svtplay_dl-1.9-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'http://www.svtplay.se/video/11794422/al-pitcher-fy-fan-sverige/al-pitcher-fy-fan-sverige-avsnitt-1?start=auto'
ERROR [1485454600.9694207] site-packages\svtplay_dl-1.9-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.9
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9-py3.5.egg\svtplay_dl\__init__.py", line 459, in main
  File "site-packages\svtplay_dl-1.9-py3.5.egg\svtplay_dl\__init__.py", line 192, in get_media
  File "site-packages\svtplay_dl-1.9-py3.5.egg\svtplay_dl\__init__.py", line 239, in get_one_media
  File "site-packages\svtplay_dl-1.9-py3.5.egg\svtplay_dl\service\svtplay.py", line 43, in get
  File "site-packages\svtplay_dl-1.9-py3.5.egg\svtplay_dl\service\svtplay.py", line 178, in outputfilename
KeyError: 'titlePagePath'
Failed to execute script svtplay-dl

**Comment by spaam** [comment] 2017-01-26 18:18
thank you for the ticket. this is a duplicate of the #528.  you can find an update for the script  later today  :)

**Closed by spaam** 2017-01-26 18:18 UTC

**Comment by Zcalman** [comment] 2017-01-26 18:20
Ah! Sorry, didnt notice the "KeyError: 'titlePagePath'" in issues.
Keep up the good work!

**Comment by spaam** [comment] 2017-01-26 18:21
@Zcalman thank you for reporting a bug so i can make the script better :)
