### ISSUE TITLE
crash in svtplay-dl

### ISSUE THREAD

**Issue by ingenvet** [spaam/svtplay-dl#531] opened 2017-01-26 17:29 UTC
DEBUG [1485451031.4141898] /usr/lib/python3.6/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/video/12051382/vanligen-lars-lerin/vanligen-lars-lerin-sasong-2-avsnitt-3'
ERROR [1485451031.4820912] /usr/lib/python3.6/site-packages/svtplay_dl/__init__.py/get_one_media: version: 1.9
Traceback (most recent call last):
File "/usr/bin/svtplay-dl", line 7, in <module>
svtplay_dl.main()
File "/usr/lib/python3.6/site-packages/svtplay_dl/__init__.py", line 459, in main
get_media(urls[0], options)
File "/usr/lib/python3.6/site-packages/svtplay_dl/__init__.py", line 192, in get_media
get_one_media(stream, options)
File "/usr/lib/python3.6/site-packages/svtplay_dl/__init__.py", line 239, in get_one_media
for i in streams:
File "/usr/lib/python3.6/site-packages/svtplay_dl/service/svtplay.py", line 43, in get
self.options.output = self.outputfilename(janson, self.options.output)
File "/usr/lib/python3.6/site-packages/svtplay_dl/service/svtplay.py", line 178, in outputfilename
name = data["video"]["titlePagePath"]
KeyError: 'titlePagePath'

**Comment by qnorsten** [comment] 2017-01-26 17:30
This is a duplicate of #528

**Comment by spaam** [comment] 2017-01-26 17:31
thank you for the ticket and @qnorsten  is right. i will release a new update later today :)

**Closed by spaam** 2017-01-26 17:31 UTC
