### ISSUE TITLE
TV4 problem

### ISSUE THREAD

**Issue by GurraH** [spaam/svtplay-dl#384] opened 2016-05-01 12:58 UTC
this is what I get when try to download from tv4play

C:\Windows\System32>c:\svtplaydll\svtplay-dl.py -S --o D:\TV "http:
.se/program/maria-wern?video_id=3294812"
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\svtplaydll\svtplay-dl.py\__main__.py", line 13, in <modu
  File "C:\svtplaydll\svtplay-dl.py\svtplay_dl\__init__.py", line 3
  File "C:\svtplaydll\svtplay-dl.py\svtplay_dl\__init__.py", line 1
dia
  File "C:\svtplaydll\svtplay-dl.py\svtplay_dl\__init__.py", line 2
e_media
  File "C:\svtplaydll\svtplay-dl.py\svtplay_dl\service\tv4play.py",
get
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1300, in XM
    parser.feed(text)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1642, in fe
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1506, in _r
    raise err
xml.etree.ElementTree.ParseError: mismatched tag: line 6, column 2

**Comment by spaam** [comment] 2016-05-01 13:02
what version is that? :)

**Comment by GurraH** [comment] 2016-05-01 13:08
I downloaded the master of svtplay 28/4

**Comment by GurraH** [comment] 2016-05-01 13:10
forgot to mention it works on tv3 and svtplay

**Comment by spaam** [comment] 2016-05-01 13:18
i cant reproduce this.  what arguments do you use?

**Comment by GurraH** [comment] 2016-05-01 13:26
c:\svtplaydll\svtplay-dl.py -S --o D:\TV "http://www.tv4play.se/program/maria-wern?video_id=3294812"

**Comment by Sopor-** [comment] 2016-05-03 12:55
@GurraH how can you run the `svtplay-dl.py` file? When i run it on Windows i either use the `svtplay-dl.exe` or i need to run `python svtplay-dl`

**Comment by GurraH** [comment] 2016-05-03 15:00
I'm not sure what you mean with run it. the line above is an autobat-file and "runs" with windows CMD.

**Comment by spaam** [comment] 2016-05-03 15:01
i will release a new version later today :)

**Comment by GurraH** [comment] 2016-05-03 15:06
ok good, I will try that one.thanks

**Comment by Sopor-** [comment] 2016-05-03 16:39
@GurraH hmm, have you renamed the `svtplay-dl` to `svtplay-dl.py`? Can it be that simple?

**Comment by GurraH** [comment] 2016-05-03 18:45
I don't think so , it works on tv3 and svt and tv4 worked a couple of days ago

**Comment by spaam** [comment] 2016-05-05 14:04
this should be fixed in the latest version 1.1.

**Closed by spaam** 2016-05-05 14:04 UTC
