### ISSUE TITLE
Can't download from tv4play.se ERROR: No videos found. You need username / password.

### ISSUE THREAD

**Issue by jarva000** [spaam/svtplay-dl#1552] opened 2023-08-19 20:39 UTC
tv4play issue
**********************************************************************'*
*  ERROR: No videos found. You need username / password. *
**********************************************************************'*
I am logged in with correct username + password

ubuntustudio 20.04 LINUX
I have tried several new 2023  LINUX distros with the same result.

$ svtplay-dl --verbose https://www.tv4play.se/video/b2f3b9f0eefb7759a576/mondo-man-v%C3%A4rldsstj%C3%A4rnan-armand-duplantis

DEBUG [1692476124.4970155] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_media: version: 4.25
DEBUG [1692476124.4986331] /usr/local/bin/svtplay-dl/svtplay_dl/service/__init__.py/__init__: service: tv4play
DEBUG [1692476124.4987006] /usr/local/bin/svtplay-dl/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.tv4play.se/video/b2f3b9f0eefb7759a576/mondo-man-v%C3%A4rldsstj%C3%A4rnan-armand-duplantis'
DEBUG [1692476124.503525] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.tv4play.se:443
DEBUG [1692476124.5637414] /usr/lib/python3/dist-packages/urllib3/connectionpool.py/_make_request: https://www.tv4play.se:443 "GET /video/b2f3b9f0eefb7759a576/mondo-man-v%C3%A4rldsstj%C3%A4rnan-armand-duplantis HTTP/1.1" 200 None
ERROR [1692476124.5694015] /usr/local/bin/svtplay-dl/svtplay_dl/utils/getmedia.py/get_one_media: No videos found. You need username / password.

$ svtplay-dl --version
svtplay-dl 4.25
$ python3 --version
Python 3.8.10
$ python2 --version
Python 2.7.18

Kernel
$ uname -r
5.15.0-79-lowlatency

$ ffmpeg -version
ffmpeg version 4.2.7

$ cat /etc/*release
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
VERSION="20.04.6 LTS (Focal Fossa)"

**Comment by spaam** [comment] 2023-08-19 20:43
it works fine here.  are you sure you are using the correct user / password? 🤔

**Comment by Sopor** [comment] 2023-08-20 00:54
I think he means that he is logged in, in the web browser ...

**Comment by Sopor** [comment] 2023-08-20 01:12
Open an editor and copy the text below and paste it in the editor.

```
default:
    subtitle: true

service:
  tv4play:
    username: <email address>
    password: <password>

```
Replace `<email address>` and `<password>` with your own and save the file to your `$HOME` directory with the name `.svtplay-dl.yaml`.

If you are running Windows you need to save it to `C:\Users\<Username>\AppData\Roaming\svtplay-dl\svtplay-dl.yaml`

Now you don't need to include username and password every time you want to download from TV4Play.

If you don't want to download subtitles for everything you download you can change `subtitle: true` to `subtitle: false`.

**Comment by SweDennis** [comment] 2023-08-20 06:06
Something is for sure going on. I just tried the supplied link above, get the same error with the correct username and password. 
Just to check and make sure I logged out of the web site, and tried to log in, and got "Something went wrong, please try later", so can't log in on web browser either ...

/Dennis

**Comment by SweDennis** [comment] 2023-08-20 18:04
Right now I'm getting "Vi upplever för tillfället problem med tjänsten. Vi jobbar på att lösa det så snabbt som möjligt" on the web front page, so let's see what status we get once solved ... That is, of course, unless spaam has some clever idea as to the reason which might be influenced by svtplay-dl ... :-D

/Dennis

**Comment by Sopor** [comment] 2023-08-21 19:43
TV4Play have changed API. The older is still there but it won't get updated.

**Comment by spaam** [comment] 2023-08-21 19:45
is there any issues right now or is the old api bad?

**Comment by Sopor** [comment] 2023-08-21 19:47
They seems to have some issues, that for sure. I don't know why.

I was logged in and i only got `Något gick fel. Försök igen.`

**Comment by SweDennis** [comment] 2023-08-22 15:09
Coming home from work today, it all works, both web page and svtplay-dl ...

svtplay-dl returned this, though, concerning the API, but then proceeded to download:

```
dennis@gentoo ~ $ svtplay-dl https://www.tv4play.se/video/b2f3b9f0eefb7759a576/mondo-man-v%C3%A4rldsstj%C3%A4rnan-armand-duplantis
/usr/bin/svtplay-dl:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('svtplay-dl==4.25', 'svtplay-dl')
```
Whatever issue they had, it seems fixed, at least here for me.

/Dennis

**Comment by buzzy** [comment] 2023-08-26 09:08
@SweDennis Fixed and fixed... the old API might still work, but it's not getting updated with content any more. A lot of videos are missing and it will get worse and worse over time. The correct thing to do would be to start using the new API.

**Comment by spaam** [comment] 2023-08-26 09:10
im going to close this ticket.  without any examples on what is missing i cant fix this issue., i will not scrape the whole site to find the issue.  feel free to send a patch with the fix :)

**Comment by buzzy** [comment] 2023-08-26 09:18
@spaam You did not even ask for specific missing videos? But sure, here are some examples:
https://github.com/retrospect-addon/plugin.video.retrospect/issues/1714

**Comment by spaam** [comment] 2023-08-26 09:21
@buzzy  if someone having issue with something they should provide info what is wrong so it will be easier to find the issue. its  like going to the doctor at the hospital without saying what is wrong and the doctor need to find out what the issue is.  pretty damn hard i would say.

**Comment by SweDennis** [comment] 2023-08-26 09:24
The password issue seems fixed, yes, which was the point of this case.
The api deprecations seems to me to be an issue all its own.

**Comment by spaam** [comment] 2023-08-26 09:25
good, some examples with the issue.. now someone can fix the issue  for us :)

**Comment by buzzy** [comment] 2023-08-26 09:29
@spaam Well, I did NOT report this issue. It was simply a response to the "everything is fine now", which it isn't. The whole "product" is crippled. And no, I don't care much, as I don't use svtplay-dl. It was simply feedback that *should* be valuable to the creator, but apparently not...

**Comment by SweDennis** [comment] 2023-08-26 09:31
@buzzy I just tested one of your supplied link above: https://www.tv4play.se/program/7fa0816013259a226175/greenland

What's not working with that one aside from the api deprecation warning?

/Dennis

**Comment by buzzy** [comment] 2023-08-26 09:33
@SweDennis I haven't looked into it personally, but I believe it's mainly listings that does not work.

**Comment by SweDennis** [comment] 2023-08-26 09:35
@buzzy Ok, you hadn't personally looked into the examples you listed as pertaining to the case at hand, I understand ...

**Comment by buzzy** [comment] 2023-08-26 09:38
@SweDennis Correct. I linked to the source of the report. I assume all details are there.

**Comment by SweDennis** [comment] 2023-08-26 09:43
@buzzy All fine with that, and I'll close with that. My whole point is that this case, 1552 has to do with an error of not being able to use username and password, which seems fixed. Other errors should be handled in separate cases, that was my whole point of saying that "All is working ...". Peace and have a great weekend.

**Comment by buzzy** [comment] 2023-08-26 09:45
@SweDennis Ok, thanks for clarifying. And yes, I agree that it should be a separate case. Great weekend to you too.

**Comment by jarva000** [comment] 2023-08-26 22:44
> svtplay-dl -S -u <username> -p <password> URL

Thank you Sopor,
now I can download from tv4play.se using your solution.
This works like a dream:
svtplay-dl -S -u mail@mail.com -p password https://www.tv4play.se/klipp/4f35ee00aa57c78554b6/guldhoppet-duplantis-klarar-610-i-f%C3%B6rsta-f%C3%B6rs%C3%B6ket?playlist=7APldpPxU4FMfj9Cz9MnTy

**Comment by SweDennis** [comment] 2023-08-27 16:36
@jarva000 If you feel as if your particular case is solved, feel free to close the case, and for further questions and new issues, open a new case.

**Comment by jarva000** [comment] 2023-08-27 21:49
I'm happy to be able to download from tv4play.se.
My particular case is solved.
Feel free to close the case.
Thanks everybody - especially Sopor.

Den sön 27 aug. 2023 kl 18:36 skrev SweDennis ***@***.***>:

**Closed** 2023-10-09 15:32 UTC
