### ISSUE TITLE
svtplay-dl crashed with titlePagePath.

### ISSUE THREAD

**Issue by maekee** [spaam/svtplay-dl#541] opened 2017-01-28 10:57 UTC
Worked for me just fine, all of a sudden this happened:
Ran this command, no links work for me any more:
svtplay-dl http://www.svtplay.se/video/1173687/sommarlagret/sommarlagret-sasong-1-avsnitt-4 --verbose

DEBUG [1485600683.96] /usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/video/1173687/sommarlagret/sommarlagret-sasong-1-avsnitt-4'
ERROR [1485600684.01] /usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py/get_one_media: version: 1.9
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 459, in main
    get_media(urls[0], options)
  File "/usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 192, in get_media
    get_one_media(stream, options)
  File "/usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 239, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/service/svtplay.py", line 43, in get
    self.options.output = self.outputfilename(janson, self.options.output)
  File "/usr/local/Cellar/svtplay-dl/1.9/libexec/lib/python2.7/site-packages/svtplay_dl/service/svtplay.py", line 178, in outputfilename
    name = data["video"]["titlePagePath"]
KeyError: 'titlePagePath'

When the problem started i had svtplay-dl 1.8, so i upgraded to 1.9 with brew install svtplay-dl.
This is my current output from brew info svtplay-dl:
svtplay-dl: stable 1.9 (bottled)
Download videos from http://svtplay.se
https://svtplay-dl.se
/usr/local/Cellar/svtplay-dl/1.8 (1,181 files, 13.4M)
  Poured from bottle on 2017-01-17 at 17:47:07
/usr/local/Cellar/svtplay-dl/1.9 (1,121 files, 12.5M) *
  Poured from bottle on 2017-01-27 at 17:25:35
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/svtplay-dl.rb
==> Dependencies
Required: rtmpdump ✔, openssl ✔
==> Caveats
To use post-processing options:
  `brew install ffmpeg` or `brew install libav`.

Also upgraded Python on my machine

**Comment by spaam** [comment] 2017-01-28 10:59
the issue is fixed in 1.9.1 and i have sent a pull request to brew so they can merge it.. they havnt done that yet.. :(

**Comment by maekee** [comment] 2017-01-28 11:06
Cool, does the download 1.9.1 from https://svtplay-dl.se/archive work on mac? How do i install when i download it? Can brew install from local package?

**Comment by iwconfig** [comment] 2017-01-28 15:21
try this oneliner in your terminal: `cd /tmp; curl -#L https://github.com/spaam/svtplay-dl/archive/master.zip | bsdtar -xf- ; sudo python setup.py install; cd -`

**Comment by spaam** [comment] 2017-01-28 17:06
what @iwconfig wrote.  they just merged 1.9.1 into brew now.  update and upgrade in brew and you will get the latest release :)

**Closed** 2017-01-28 17:09 UTC
