### ISSUE TITLE
Problem with downloading svtplay url

### ISSUE THREAD

**Issue by ilbaritone** [spaam/svtplay-dl#455] opened 2016-09-18 21:38 UTC
I get an error message when I try to download: http://www.svtplay.se/video/7515710/anno-1790/anno-1790-sasong-1-avsnitt-4
This is what I got when I run --verbose:
svtplay-dl --verbose http://www.svtplay.se/video/7515710/anno-1790/anno-1790-sasong-1-avsnitt-4
DEBUG [1474233961.76] /usr/local/Cellar/svtplay-dl/1.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://www.svtplay.se/video/7515710/anno-1790/anno-1790-sasong-1-avsnitt-4'
DEBUG [1474233962.63] /usr/local/Cellar/svtplay-dl/1.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://www.svt.se/videoplayer-api/video/1136646-004A'
DEBUG [1474233962.97] /usr/local/Cellar/svtplay-dl/1.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay11r-f.akamaihd.net/z/se/open/20160401/1136646-004A/PG-1136646-004A-ANNO1790-01_,988,240,348,456,636,1680,2796,.mp4.csmil/manifest.f4m'
DEBUG [1474233963.73] /usr/local/Cellar/svtplay-dl/1.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://svtplay11f-f.akamaihd.net/d/se/open/delivery/20160401/1136646-004A/dash-ondemand/PG-1136646-004A-ANNO1790-01-6f0049ca-b461-336d-9088-c9ffa7f429c1-ondemand.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F1136646-004A.mpd'
DEBUG [1474233964.7] /usr/local/Cellar/svtplay-dl/1.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting u'http://switcher.cdn.svt.se/1136646-004A.mpd'
DEBUG [1474233966.26] /usr/local/Cellar/svtplay-dl/1.4/libexec/lib/python2.7/site-packages/svtplay_dl/utils/__init__.py/request: HTTP getting 'http://ed1.cdn.svt.se/vod/_definst_/amlst:20160401/1136646-004A/PG-1136646-004A-ANNO1790-01/manifest.mpd'
ERROR [1474233966.33] /usr/local/Cellar/svtplay-dl/1.4/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py/get_one_media: version: 1.4
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/1.4/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 444, in main
    get_media(url, options)
  File "/usr/local/Cellar/svtplay-dl/1.4/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 178, in get_media
    get_one_media(stream, options)
  File "/usr/local/Cellar/svtplay-dl/1.4/libexec/lib/python2.7/site-packages/svtplay_dl/__init__.py", line 225, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/1.4/libexec/lib/python2.7/site-packages/svtplay_dl/service/svtplay.py", line 119, in get
    streams = dashparse(self.options, self.http.request("get", alt.request.url), alt.request.url)
  File "/usr/local/Cellar/svtplay-dl/1.4/libexec/lib/python2.7/site-packages/svtplay_dl/fetcher/dash.py", line 33, in dashparse
    baseurl = urljoin(url, xml.find("{urn:mpeg:dash:schema:mpd:2011}BaseURL").text)
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by spaam** [comment] 2016-09-18 21:44
this is a dupe of #448. i will release a fix for this tomorrow :)

**Closed by spaam** 2016-09-18 21:44 UTC

**Comment by ilbaritone** [comment] 2016-09-19 04:35
Thanks!
