### ISSUE TITLE
No sound from TV4

### ISSUE THREAD

**Issue by Usudanix** [spaam/svtplay-dl#1162] opened 2019-09-24 05:25 UTC
Tried to Download the TV4 mini serie "Kapten Klänning".
Video and subtitles went fine. But there is no sound.

Anyone else having this problem?

svtplay-dl 2.4-20-g0826b8f
Linux Ubuntu: 18.04

### Operating system and Python version:

Python 2.7.15+

### What is the issue:

svtplay-dl https://www.tv4play.se/program/kapten-kl%C3%A4nning-polischef-och-v%C3%A5ldt%C3%A4ktsman --subtitle --all-episodes -u xxxx@xxxx.xxx -p xxxxxx

**Comment by SweDennis** [comment] 2019-09-24 14:01
I couldn't get this to work either, same version as you, but I had a different issue. Using --all-episodes, the download didn't even begin, and with verbose active the screen just rolled and rolled with endless tries. It DID work for me with a single download of episode 1 however, with no sound issues at all.

On a side not, however, I do experience the no sound rather regularly, on svtplay.se and dash streams. The solution there seems to be to use -P hls and using that I've never had sound issues.

**Comment by Sopor** [comment] 2019-09-24 14:29
If you update ffmpeg to 4 or higher the sound will work.

**Comment by Sopor** [comment] 2019-09-24 14:35
As you can see here it is working perfect:

```
svtplay-dl.exe -A -S -P hls https://www.tv4play.se/program/kapten-kl%C3%A4nning-polischef-och-v%C3%A5ldt%C3%A4ktsman
INFO: Episode 1 of 3
INFO: Url: https://www.tv4play.se/program/kapten-klänning-polischef-och-våldtäktsman/11982231
INFO: Outfile: kapten-klanning-polischef-och-valdtaktsman.s01e01.kapten.klanning-polischef.och.valdtaktsman.del.1-11982231-tv4play.srt
INFO: Selected to download hls, bitrate: 3915
INFO: Outfile: kapten-klanning-polischef-och-valdtaktsman.s01e01.kapten.klanning-polischef.och.valdtaktsman.del.1-11982231-tv4play.audio.ts
[019/660][==..............................................................................] ETA: 0:01:21
```

**Comment by Sopor** [comment] 2019-09-24 14:52
@SweDennis Did you use `-S`? It takes 30 to 60 seconds (sometimes even more) to download the subtitles. Did you waited that long?

**Comment by SweDennis** [comment] 2019-09-24 14:53
I did, but only in order to mimic the original posters command. I never do this personally, so that can very well be the case and the cause of my issue. Will try and wait a bit longer.

**Comment by SweDennis** [comment] 2019-09-24 14:55
Works just fine, if I just wait a bit longer. Learn something new every day, sorry for the confusion.

**Comment by Usudanix** [comment] 2019-09-24 17:15
> If you update ffmpeg to 4 or higher the sound will work.
> 
> @Usudanix You don't need to use -u and -p to download non premium episodes

Thanks @Sopor !
Upgrading to ffmpeg 4.2 did the trick!! :)

**Comment by Sopor** [comment] 2019-09-24 20:48
@Usudanix if the issue is solved, you should close it...

**Closed** 2019-09-25 05:26 UTC
