### ISSUE TITLE
Subtitles from Viafree.

### ISSUE THREAD

**Issue by Swedie** [spaam/svtplay-dl#749] opened 2017-12-14 20:30 UTC
Trying to download subtitles from Viafree using -S and --force-subtitle. Running 1.9.6 on windows 10, worked two days ago, so I'm assuming someting has changed :)

`svtplay-dl.exe -S --force-subtitle --verbose https://www.viafree.se/program/livsstil/masterchef-usa/sasong-8/avsnitt-19
DEBUG [1513283311.8211873] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\utils\__init__.py/request: HTTP getting 'https://www.viafree.se/program/livsstil/masterchef-usa/sasong-8/avsnitt-19'
ERROR [1513283312.0891633] site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py/get_one_media: version: 1.9.6
Traceback (most recent call last):
  File "svtplay-dl", line 7, in <module>
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 477, in main
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 199, in get_media
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\__init__.py", line 247, in get_one_media
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\service\viaplay.py", line 107, in get
  File "site-packages\svtplay_dl-1.9.6-py3.5.egg\svtplay_dl\service\viaplay.py", line 87, in _get_video_id
  File "json\__init__.py", line 319, in loads
  File "json\decoder.py", line 342, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 55670 (char 55669)
Failed to execute script svtplay-dl`

**Comment by crapmaster** [comment] 2018-01-03 19:32
Think this also is a duplicate of #748.
At least I can download the subtitle in you bug report using pull request #753.

**Comment by spaam** [comment] 2018-02-22 04:06
this should be fixed in 1.9.7

**Closed by spaam** 2018-02-22 04:06 UTC
