### ISSUE TITLE
Svtplay-dl crash

### ISSUE THREAD

**Issue by oskmat** [spaam/svtplay-dl#1055] opened 2019-03-23 16:23 UTC
### svtplay-dl versions:
svtplay-dl --version
svtplay-dl 2.1

### Operating system and Python version:
MacOS 10.14.3 (18D109)
python --version
Python 2.7.16

### What is the issue:

svtplay-dl --verbose https://www.svtplay.se/video/21589910/langdskidor-varldscupen/langdskidor-varldscupen-sprint-fristil

DEBUG [1553358003.746279] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 2.1
DEBUG [1553358003.7474198] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1553358003.747487] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/21589910/langdskidor-varldscupen/langdskidor-varldscupen-sprint-fristil'
DEBUG [1553358003.755139] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1553358003.892861] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/21589910/langdskidor-varldscupen/langdskidor-varldscupen-sprint-fristil HTTP/1.1" 200 45028
DEBUG [1553358003.929378] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1392027-001W'
DEBUG [1553358003.9313269] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): api.svt.se:80
DEBUG [1553358003.994812] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://api.svt.se:80 "GET /videoplayer-api/video/1392027-001W HTTP/1.1" 200 753
DEBUG [1553358003.99554] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/8098c79c-75a4-4706-8a15-453050a17097/master-lowbw.m3u8'
DEBUG [1553358003.9965131] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): switcher.cdn.svt.se:80
DEBUG [1553358004.068087] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /8098c79c-75a4-4706-8a15-453050a17097/master-lowbw.m3u8 HTTP/1.1" 302 0
DEBUG [1553358004.069469] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): svt-vod-4d.akamaized.net:80
DEBUG [1553358004.1430988] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-4d.akamaized.net:80 "GET /se/20190322/8098c79c-75a4-4706-8a15-453050a17097/master-lowbw.m3u8 HTTP/1.1" 200 402
DEBUG [1553358004.143609] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/8098c79c-75a4-4706-8a15-453050a17097/lowbw.mpd'
DEBUG [1553358004.168751] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /8098c79c-75a4-4706-8a15-453050a17097/lowbw.mpd HTTP/1.1" 302 0
DEBUG [1553358004.1975412] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-4d.akamaized.net:80 "GET /se/20190322/8098c79c-75a4-4706-8a15-453050a17097/lowbw.mpd HTTP/1.1" 200 751
DEBUG [1553358004.199229] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/8098c79c-75a4-4706-8a15-453050a17097/manifest.mpd'
DEBUG [1553358004.2242439] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /8098c79c-75a4-4706-8a15-453050a17097/manifest.mpd HTTP/1.1" 302 0
DEBUG [1553358004.251625] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-4d.akamaized.net:80 "GET /se/20190322/8098c79c-75a4-4706-8a15-453050a17097/manifest.mpd HTTP/1.1" 200 849
DEBUG [1553358004.2522109] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://svt-vod-4d.akamaized.net/se/20190322/8098c79c-75a4-4706-8a15-453050a17097/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F8098c79c-75a4-4706-8a15-453050a17097%2Fmanifest.mpd'
DEBUG [1553358004.278872] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-4d.akamaized.net:80 "GET /se/20190322/8098c79c-75a4-4706-8a15-453050a17097/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F8098c79c-75a4-4706-8a15-453050a17097%2Fmanifest.mpd HTTP/1.1" 200 849
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/__init__.py", line 64, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 58, in get_media
    get_one_media(stream)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 107, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/service/svtplay.py", line 86, in get
    for i in videos:
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/service/svtplay.py", line 122, in _get_video
    streams = dashparse(self.config, self.http.request("get", i["url"]), i["url"], output=self.output)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 143, in dashparse
    return _dashparse(config, res.text, url, output, res.cookies)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 171, in _dashparse
    audiofiles = adaptionset(temp, url, baseurl, offset_sec, duration_sec)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 102, in adaptionset
    template = element[0].find("{urn:mpeg:dash:schema:mpd:2011}SegmentTemplate")
IndexError: list index out of range

**Comment by Sopor** [comment] 2019-03-23 18:34
Dupe of #1054 and fixed in latest master

**Comment by spaam** [comment] 2019-04-08 21:26
this is fixed in master. will releasing 2.2 tomorrow or the day after.  thanks for the report. <3

**Closed by spaam** 2019-04-08 21:26 UTC

**Comment by oskmat** [comment] 2019-04-09 04:14
Du ska ha tack!

**Comment by thaofus** [comment] 2019-05-01 20:07
same issue?:
svtplay-dl https://www.svtplay.se/video/21795990/lunds-studentsangare --verbose
DEBUG [1556740910.050099] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py/get_media: version: 2.1
DEBUG [1556740910.05228] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/service/__init__.py/__init__: service: svtplay
DEBUG [1556740910.052398] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'https://www.svtplay.se/video/21795990/lunds-studentsangare'
DEBUG [1556740910.058155] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTPS connection (1): www.svtplay.se:443
DEBUG [1556740910.38112] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: https://www.svtplay.se:443 "GET /video/21795990/lunds-studentsangare HTTP/1.1" 200 35625
DEBUG [1556740910.3979762] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://api.svt.se/videoplayer-api/video/1392964-001A'
DEBUG [1556740910.399978] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): api.svt.se:80
DEBUG [1556740910.506942] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://api.svt.se:80 "GET /videoplayer-api/video/1392964-001A HTTP/1.1" 200 755
DEBUG [1556740910.509239] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/039287e8-8300-49ab-b5f1-25828f0ef505/master-fmp4.m3u8'
DEBUG [1556740910.511658] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): switcher.cdn.svt.se:80
DEBUG [1556740911.2921011] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /039287e8-8300-49ab-b5f1-25828f0ef505/master-fmp4.m3u8 HTTP/1.1" 302 0
DEBUG [1556740911.2948322] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_new_conn: Starting new HTTP connection (1): svt-vod-2c.akamaized.net:80
DEBUG [1556740911.414158] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-2c.akamaized.net:80 "GET /d0/world/20190501/039287e8-8300-49ab-b5f1-25828f0ef505/master-fmp4.m3u8 HTTP/1.1" 200 596
DEBUG [1556740911.4156559] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/039287e8-8300-49ab-b5f1-25828f0ef505/lowbw.mpd'
DEBUG [1556740911.490525] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /039287e8-8300-49ab-b5f1-25828f0ef505/lowbw.mpd HTTP/1.1" 302 0
DEBUG [1556740911.588789] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-2c.akamaized.net:80 "GET /d0/world/20190501/039287e8-8300-49ab-b5f1-25828f0ef505/lowbw.mpd HTTP/1.1" 200 811
DEBUG [1556740911.590135] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://switcher.cdn.svt.se/039287e8-8300-49ab-b5f1-25828f0ef505/manifest.mpd'
DEBUG [1556740911.658195] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://switcher.cdn.svt.se:80 "GET /039287e8-8300-49ab-b5f1-25828f0ef505/manifest.mpd HTTP/1.1" 302 0
DEBUG [1556740911.7457962] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-2c.akamaized.net:80 "GET /d0/world/20190501/039287e8-8300-49ab-b5f1-25828f0ef505/manifest.mpd HTTP/1.1" 200 909
DEBUG [1556740911.746495] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/http.py/request: HTTP getting 'http://svt-vod-2c.akamaized.net/d0/world/20190501/039287e8-8300-49ab-b5f1-25828f0ef505/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F039287e8-8300-49ab-b5f1-25828f0ef505%2Fmanifest.mpd'
DEBUG [1556740911.83075] /usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/urllib3/connectionpool.py/_make_request: http://svt-vod-2c.akamaized.net:80 "GET /d0/world/20190501/039287e8-8300-49ab-b5f1-25828f0ef505/manifest.mpd?alt=http%3A%2F%2Fswitcher.cdn.svt.se%2F039287e8-8300-49ab-b5f1-25828f0ef505%2Fmanifest.mpd HTTP/1.1" 200 909
Traceback (most recent call last):
  File "/usr/local/bin/svtplay-dl", line 7, in <module>
    svtplay_dl.main()
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/__init__.py", line 64, in main
    get_media(urls[0], config, __version__)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 58, in get_media
    get_one_media(stream)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/utils/getmedia.py", line 107, in get_one_media
    for i in streams:
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/service/svtplay.py", line 86, in get
    for i in videos:
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/service/svtplay.py", line 122, in _get_video
    streams = dashparse(self.config, self.http.request("get", i["url"]), i["url"], output=self.output)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 143, in dashparse
    return _dashparse(config, res.text, url, output, res.cookies)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 171, in _dashparse
    audiofiles = adaptionset(temp, url, baseurl, offset_sec, duration_sec)
  File "/usr/local/Cellar/svtplay-dl/2.1/libexec/lib/python3.7/site-packages/svtplay_dl/fetcher/dash.py", line 102, in adaptionset
    template = element[0].find("{urn:mpeg:dash:schema:mpd:2011}SegmentTemplate")
IndexError: list index out of range

**Comment by Ferbd-Git** [comment] 2019-05-15 11:34
Where is the last master to download and install?

**Comment by Sopor** [comment] 2019-05-16 21:47
@Ferbd-Git 

- [Windows](https://ci.appveyor.com/project/spaam/svtplay-dl/builds/23825288/artifacts)
- [MacOS](https://github.com/spaam/svtplay-dl/issues/1070#issuecomment-488087551) or use Linux below.
- [Linux](https://svtplay-dl.se/install/source/)

**Comment by Ferbd-Git** [comment] 2019-05-17 07:10
Sopor, tack så mycket för ditt svar. Jag kunde installera i Ubuntu och min fru är mycket glad därför att hon kan se nu "Vem bor här?" från svtplay.
Stor tack!

**Comment by Ferbd-Git** [comment] 2019-05-17 17:35
Hej Sopor! Jag laddade ner "Vem bor här", jag får filmen men ljudet blir bra de första sekunderna bara, sedan blir helt stumt.
Någonting som är fel alltså.

**Comment by Sopor** [comment] 2019-05-17 19:18
@Ferbd-Git Det låter som om du behöver uppdatera ffmpeg. Du måste ha version 4.0 eller högre.

**Comment by Ferbd-Git** [comment] 2019-05-18 16:04
Hej Sopor, tack för informationen, jag installerade ffmpeg 4 och felet har försvunnit, nu finns audio med hela vägen.
